#!/usr/bin/env python3
"""Generate the camera-ready LaTeX tables from results/*.json. Never hand-type numbers.

Run:  python analysis/make_tables.py        (from CR; writes paper/tables/*.tex)

Every file starts with a provenance line naming its source JSONs. Conventions:
  * mean +- SAMPLE SD over seeds (ddof=1), 2 dp unless stated;
  * paired deltas / CIs come from the 5000-resample paired bootstraps in results/;
  * in the merged dissociation table the Range row is computed from the UNROUNDED means
    (verifier fix: the submitted Table 3 used the printed 2-dp means, which gave an S2-TTA
    range of 0.27 pp instead of 0.28 pp); probe / ladder spans are of unrounded means too.
Tables use booktabs only.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import config as C  # noqa: E402

PROT = list(C.PROTOCOLS)
SEEDS = [str(s) for s in C.SEEDS]
OUT = C.TABLES


def J(name):
    return json.load(open(C.RESULTS / f"{name}.json"))


def header(sources):
    srcs = ", ".join(f"results/{s}.json" for s in sources)
    return f"% AUTO-GENERATED by analysis/make_tables.py from {srcs} — do not hand-edit\n"


def write(name, sources, body):
    p = OUT / f"{name}.tex"
    with open(p, "w") as f:
        f.write(header(sources))
        f.write(body.rstrip() + "\n")
    print(f"wrote paper/tables/{name}.tex")


# ----------------------------------------------------------------------------- formatting
def num(x, nd=2):
    return f"{x:.{nd}f}"


def pm(agg, nd=2, sdnd=None):
    sdnd = nd if sdnd is None else sdnd
    return f"${agg['mean']:.{nd}f}\\!\\pm\\!{agg['sd']:.{sdnd}f}$"


def sg(x, nd=2):
    return f"${x:+.{nd}f}$"


def ci(pooled, nd=2, key_d="delta_pp"):
    d, (lo, hi) = pooled[key_d], pooled["ci95_pp"]
    return f"${d:+.{nd}f}$\\,[${lo:+.{nd}f}$,\\,${hi:+.{nd}f}$]"


def pm1(pooled_list):
    """'Yes' if every CI lies inside (-1, +1) pp, else 'No (<protocols>)'."""
    bad = [p for p, q in pooled_list if not q["within_pm1pp"]]
    return "Yes" if not bad else "\\begin{tabular}[t]{@{}l@{}}No (" + ",\\\\".join(bad) + ")\\end{tabular}"


# ============================================================================= B1: merged dissociation table
def t_dissociation_merged():
    trio, mgc = J("c100_trio"), J("mgc_c100")
    tp, mp, c10 = J("c100_trio_paired"), J("mgc_paired_bootstrap"), J("c10_paired")
    V = trio["variants"]
    rows = []

    def acc_row(label, agg, sep_agg, bold=None):
        cells = [label, pm(sep_agg)] + [pm(agg[p]) for p in PROT] + [""]
        return " & ".join(cells) + " \\\\"

    def delta_row(pairs):
        cells = ["\\quad $\\Delta$ vs.\\ cum.", ""] + [ci(q) for _, q in pairs] + [pm1(pairs)]
        return " & ".join(cells) + " \\\\"

    rows.append(acc_row("$\\gamma{=}0$", V["gamma0"]["agg"], V["gamma0"]["agg"]["sep_curr_nl_deepest"]))
    rows.append(delta_row([(p, tp["pairs"][p]["gamma0_minus_cumulative"]["pooled"]) for p in PROT]))
    rows.append(acc_row("Gated $\\kappa{=}0$", V["gated_k0"]["agg"], V["gated_k0"]["agg"]["sep_curr_nl_deepest"]))
    rows.append(delta_row([(p, tp["pairs"][p]["gated_k0_minus_cumulative"]["pooled"]) for p in PROT]))
    rows.append(acc_row("Cumulative", V["cumulative"]["agg"], V["cumulative"]["agg"]["sep_curr_nl_deepest"]))
    rows.append(acc_row("MGC", mgc["mgc"]["agg"], mgc["mgc"]["agg"]["sep_curr_nl_deepest"]))
    rows.append(delta_row([(p, mp["mgc_minus_cumulative"][p]["pooled"]) for p in PROT]))
    fv = mgc["four_variant_c100"]
    rng = fv["range_pp_per_protocol"]
    range_row = " & ".join(["Range", f"${fv['deepest_sep_max_over_min_unrounded']:.2f}{{\\times}}$"]
                           + [f"${rng[p]:.2f}$\\,pp" for p in PROT] + [""]) + " \\\\"
    c10p = c10["cp_fair_minus_gamma0"]
    c10_row = " & ".join(["C10 pair", "---"]
                         + [ci(c10p[p]["pooled"]) for p in PROT]
                         + [pm1([(p, {"within_pm1pp": c10p[p]["pooled"]["within_pm1pp"]}) for p in PROT])]) + " \\\\"
    minp = c10["min_mcnemar_p_tta_protocols_floor_2dp"]
    # Phase 6 (B1): this table replaces the submitted main-text Table 3 and absorbs the appendix
    # duplicates (tab:dissociation, tab:paired_dissociation, tab:dissociation_ci). Writing pass
    # (reviewer-audit items): the interpretive caption sentences (heuristic repairs / MGC Stage-1 cost /
    # accuracy invariance with the 13--26% churn range) are dropped because Sec. 4.5 states them; the
    # S1 caveat for gamma=0 and gated stays. All three trio arms carry the depth-scaled auxiliary
    # (block_curr_lambda=0.25, slope 3.0 in every trio config.json); MGC replaces it.
    # Verifier round (F19): the heuristic repairs' S1 CIs vs cumulative exclude 0 (inside +-1 pp);
    # gamma=0's S1-TTA CI does too. Assert so the caption sentence cannot go stale silently.
    heur = {v: tp["pairs"][p][f"{v}_minus_cumulative"]["pooled"] for v in ("gamma0", "gated_k0") for p in ("S1",)}
    assert all(q["ci95_pp"][1] < 0 and q["within_pm1pp"] for q in heur.values()), heur
    g0_s1tta = tp["pairs"]["S1-TTA"]["gamma0_minus_cumulative"]["pooled"]["ci95_pp"]
    k0_s1tta = tp["pairs"]["S1-TTA"]["gated_k0_minus_cumulative"]["pooled"]["ci95_pp"]
    assert g0_s1tta[1] < 0 and not (k0_s1tta[1] < 0), (g0_s1tta, k0_s1tta)
    # Verifier round (F5): resumed trio runs = layer log starting after epoch 1 (each has an earlier
    # aborted directory holding epochs 1..N-1); MGC seed 456 is the fourth-arm resume.
    resumed_trio = sum(1 for v in V.values() for ps in v["per_seed"].values() if ps["first_stage1_epoch_logged"] > 1)
    n_trio = sum(len(v["per_seed"]) for v in V.values())
    assert mgc["mgc"]["per_seed"]["456"]["first_stage1_epoch_logged"] > 1
    body = rf"""\begin{{table}}[!tb]
  \caption{{\textbf{{Central dissociation under four readout protocols (CIFAR-100, dense L4/D256, 3~seeds).}}
           sep: deepest-block $\text{{sep}}^\text{{cur}}_\text{{nl}}$ (L3) at the last Stage-1 epoch.
           Accuracy: test top-1 (\%) of the validation-selected checkpoints (S1: EMA backbone; S2: trained head
           on the frozen EMA backbone), mean $\pm$ sample SD.
           The trio arms differ only in the history rule ($\gamma{{=}}0$; gated: hardness-gated $\kappa{{=}}0$;
           cumulative: $\gamma{{=}}0.7$) and all carry the depth-scaled auxiliary of Eq.~\ref{{eq:depth_scaled_main}};
           MGC ($c_d{{=}}1$, \S\ref{{sec:repairs}}) replaces that auxiliary by the compensator.
           $\Delta$ rows: paired difference to the cumulative arm on matched seeds ($n{{=}}30{{,}}000$ test
           predictions) with a 5000-resample bootstrap 95\% CI, conditional on the trained checkpoints;
           per-seed deltas are in App.~\ref{{app:mgc_results}} (MGC) and App.~\ref{{app:churn}} (trio).
           ``$\pm1$\,pp?'': every CI lies inside $\pm1$\,pp. Range: max/min ratio for sep and max$-$min for
           accuracy, over the unrounded variant means. $\gamma{{=}}0$ and gated sit slightly below cumulative
           at S1 ($\gamma{{=}}0$ also at S1-TTA), with CIs that exclude 0 but stay inside $\pm1$\,pp.
           MGC seed~456 and {resumed_trio} of the {n_trio} trio runs
           were resumed from checkpoints (App.~Tabs.~\ref{{tab:mgc_full}}
           and~\ref{{tab:cifar100_dissociation_multiseed}}). C10 pair: $\Delta$ [95\% CI] of \textsc{{cp-fair}} $-$ $\gamma{{=}}0$ on CIFAR-10
           (L4/D256, 3 seeds $\times$ 10k test images; per-seed exact McNemar $p{{>}}{minp:.2f}$ under TTA;
           $\gamma{{=}}0$ seed-42 note in \S\ref{{sec:setup}}).}}
  \label{{tab:dissociation_merged}}
  \centering
  \footnotesize
  \setlength{{\tabcolsep}}{{1.5pt}}
  \resizebox{{\textwidth}}{{!}}{{%
  \begin{{tabular}}{{lcccccl}}
    \toprule
    Variant & sep (L3) & S1 & S1-TTA & S2 & S2-TTA & $\pm1$\,pp? \\
    \midrule
""" + "\n".join("    " + r for r in rows) + rf"""
    \midrule
    {range_row}
    \midrule
    {c10_row}
    \bottomrule
  \end{{tabular}}%
  }}
\end{{table}}
"""
    write("t_dissociation_merged", ["c100_trio", "mgc_c100", "c100_trio_paired", "mgc_paired_bootstrap", "c10_paired"], body)


# ============================================================================= C1/C2: MGC per-seed table
def t_mgc():
    m, d = J("mgc_c100"), J("mgc_d128")
    rows = []
    mg, cum, dl = m["mgc"], m["cumulative"], m["delta_mgc_minus_cumulative_pp"]
    for i, s in enumerate(SEEDS):
        ps = mg["per_seed"][s]
        acc = [f"{ps[p]:.2f} (${dl[p]['values'][i]:+.2f}$)" for p in PROT]
        sep = [num(x) for x in ps["sep_curr_nl"]]
        lam = [num(x) for x in ps["lam_mean_final"][1:]]
        tag = s + ("$^\\dagger$" if s == "456" else "")
        rows.append(" & ".join(([r"\multirow{5}{*}{\shortstack[l]{CIFAR-100\\L4/D256\\(SAM off)}}"] if i == 0 else [""]) + [tag] + acc + sep + lam) + " \\\\")
    a = mg["agg"]
    rows.append(" & ".join(["", "mean"] + [f"{a[p]['mean']:.2f}$\\pm${a[p]['sd']:.2f} (${dl[p]['mean']:+.2f}$)" for p in PROT]
                           + [f"{x['mean']:.2f}$\\pm${x['sd']:.2f}" for x in a["sep_curr_nl_per_block"]]
                           + [num(x["mean"]) for x in a["lam_mean_final_per_block"][1:]]) + " \\\\")
    c = cum["agg"]
    rows.append(" & ".join(["", "cum."] + [f"{c[p]['mean']:.2f}$\\pm${c[p]['sd']:.2f}" for p in PROT]
                           + [f"{x['mean']:.2f}$\\pm${x['sd']:.2f}" for x in c["sep_curr_nl_per_block"]] + ["---"] * 3) + " \\\\")
    rows.append("\\midrule")
    g = d["mgc"]
    for i, s in enumerate(SEEDS):
        ps = g["per_seed"][s]
        rows.append(" & ".join(([r"\multirow{4}{*}{\shortstack[l]{CIFAR-10\\L4/D128\\(SAM on)}}"] if i == 0 else [""])
                               + [s + ("$^\\ddagger$" if s == "42" else "")] + [f"{ps[p]:.2f}" for p in PROT]
                               + [num(x) for x in ps["sep_curr_nl"]] + [num(x) for x in ps["lam_mean_final"][1:]]) + " \\\\")
    a = g["agg"]
    rows.append(" & ".join(["", "mean"] + [f"{a[p]['mean']:.2f}$\\pm${a[p]['sd']:.2f}" for p in PROT]
                           + [f"{x['mean']:.2f}$\\pm${x['sd']:.2f}" for x in a["sep_curr_nl_per_block"]]
                           + [num(x["mean"]) for x in a["lam_mean_final_per_block"][1:]]) + " \\\\")
    lw = m["lambda_telemetry"]["seed42_whole_training_mean_lambda_per_block"][1:]
    anc = d["seed42_sam_off_anchors"]
    # Verifier round (F3): list every anchor under S1, S1-TTA and S2-TTA, not only the S1 values, so the
    # caption shows that MGC's L4/D128 gap is single-crop S1 only (S1-TTA ties gamma=0, S2-TTA ties kappa=0).
    ak = ("gamma07_constant", "gamma0_no_all_collab", "gated_k0_t1")

    def anc3(p):
        return "/".join(num(anc[k][p]) for k in ak)

    body = rf"""\begin{{table}}[!htb]
  \caption{{\textbf{{Missing-gradient compensation (MGC, $c_d{{=}}1$) per seed.}} Test top-1 (\%) of
           the validation-selected EMA checkpoints; in parentheses, the paired difference to the
           cumulative ($\gamma{{=}}0.7$) arm on the same seed. sep: $\text{{sep}}^\text{{cur}}_\text{{nl}}$
           per block at the last Stage-1 epoch; $\bar\lambda$: final-epoch mean compensation weight
           (block~0 has no compensator, $\bar\lambda{{\equiv}}0$). The MGC arm replaces the baseline's
           depth-scaled current-block term, so block~0 also loses its auxiliary. Seed-42 whole-training
           mean $\bar\lambda$ (CIFAR-100): {num(lw[0])}/{num(lw[1])}/{num(lw[2])}.
           Faithful implementation ($\epsilon{{=}}10^{{-6}}$, positive-part clamp; only the mean and p95
           of $\lambda$ are logged). $^\dagger$Resumed run: layer log starts at epoch
           {m['mgc']['per_seed']['456']['first_stage1_epoch_logged']} (final evaluation complete).
           $^\ddagger$Local run; seeds 123/456 ran on Colab. The seed-42 L4/D128 SAM-off anchors
           ($\gamma{{=}}0.7$/$\gamma{{=}}0$/$\kappa{{=}}0$) reach S1 {anc3('S1')}, S1-TTA {anc3('S1-TTA')}, and
           S2-TTA {anc3('S2-TTA')}; these single-seed comparisons cross the SAM setting (SAM-matched
           cumulative arm: Table~\ref{{tab:f1_control}}).}}
  \label{{tab:mgc_full}}
  \centering
  \scriptsize
  \setlength{{\tabcolsep}}{{2pt}}
  \resizebox{{\textwidth}}{{!}}{{%
  \begin{{tabular}}{{llccccccccccc}}
    \toprule
    & & \multicolumn{{4}}{{c}}{{Test top-1 (\%)}} & \multicolumn{{4}}{{c}}{{$\text{{sep}}^\text{{cur}}_\text{{nl}}$ per block}} & \multicolumn{{3}}{{c}}{{$\bar\lambda$ per block}} \\
    \cmidrule(lr){{3-6}} \cmidrule(lr){{7-10}} \cmidrule(lr){{11-13}}
    Setting & Seed & S1 & S1-TTA & S2 & S2-TTA & L0 & L1 & L2 & L3 & L1 & L2 & L3 \\
    \midrule
""" + "\n".join("    " + r for r in rows) + r"""
    \bottomrule
  \end{tabular}%
  }
\end{table}
"""
    write("t_mgc", ["mgc_c100", "mgc_d128"], body)


# ============================================================================= C5: squared hinge
def t_hinge():
    h = J("hinge")
    A = h["arms"]
    rows = []
    for key, label in (("gamma0.7", "Cumulative $\\gamma{=}0.7$"), ("gamma0", "History-free $\\gamma{=}0$")):
        a = A[key]["agg"]
        sepb = a["sep_curr_nl_per_block"]
        rows.append(" & ".join([label] + [pm(a[p]) for p in PROT] + [pm(sepb[0]), pm(sepb[-1])]) + " \\\\")
    dd = h["delta_gamma07_minus_gamma0_pp"]
    rows.append("\\midrule")
    rows.append(" & ".join(["$\\Delta$ ($\\gamma{=}0.7$ $-$ $\\gamma{=}0$); sep ratio $\\gamma{=}0/\\gamma{=}0.7$"] + [sg(dd[p]) for p in PROT]
                           + ["---", f"${h['deepest_sep_ratio_gamma0_over_gamma07']:.2f}{{\\times}}$"]) + " \\\\")
    body = rf"""\begin{{table}}[!htb]
  \caption{{\textbf{{Squared-hinge replication}} (barrier $\max(0,\theta-u)^2$, $\theta{{=}}2$; CIFAR-10
           L4/D128, 180+10 epochs, SAM on, 3 seeds per arm, mean $\pm$ sample SD). The deepest block
           loses separation under the cumulative objective while block~0 is unchanged, and test
           accuracy differs between the arms by at most {num(max(abs(v) for v in dd.values()))}\,pp. All seeds come from one run lineage; the
           $\gamma{{=}}0.7$ seed-456 layer log is a resumed suffix starting at epoch
           {h['arms']['gamma0.7']['per_seed']['456']['first_stage1_epoch_logged']}.}}
  \label{{tab:hinge}}
  \centering
  \small
  \setlength{{\tabcolsep}}{{3pt}}
  \resizebox{{\textwidth}}{{!}}{{%
  \begin{{tabular}}{{lcccccc}}
    \toprule
    Arm & S1 & S1-TTA & S2 & S2-TTA & sep (L0) & sep (L3) \\
    \midrule
""" + "\n".join("    " + r for r in rows) + r"""
    \bottomrule
  \end{tabular}%
  }
\end{table}
"""
    write("t_hinge", ["hinge"], body)


# ============================================================================= C7: gradient share
def t_gradshare():
    g = J("gradient_share")
    A = g["arms"]

    def cells(arm, term):
        out = []
        for b in A[arm]["per_block"]:
            t = b["terms"].get(term)
            out.append("---" if t is None else f"{t['share']:.3f} ({t['cos']:.2f})")
        return out

    rows = [
        " & ".join(["$\\gamma{=}0.7$ (constant)", "discrimination (cum.)"] + cells("gamma0.7", "block_cum")) + " \\\\",
        " & ".join(["", "current-block aux."] + cells("gamma0.7", "block_curr")) + " \\\\",
        " & ".join(["$\\gamma{=}0$", "discrimination (cum.)"] + cells("gamma0", "block_cum")) + " \\\\",
        " & ".join(["MGC ($c_d{=}1$)", "discrimination (cum.)"] + cells("mgc", "block_cum")) + " \\\\",
        " & ".join(["", "MGC local term"] + cells("mgc", "mgc_local")) + " \\\\",
    ]
    nb = A["mgc"]["n_batches"]
    body = rf"""\begin{{table}}[!htb]
  \caption{{\textbf{{Per-term gradient share at convergence}} (seed~42, CIFAR-10 L4/D128 gated-ablation
           arms and MGC; raw training weights, not EMA). Share $=\|\nabla_t\|/\|\nabla_\text{{total}}\|$
           over each block's own parameters, mean over {nb} training batches; in parentheses
           $\cos(\nabla_t,\nabla_\text{{total}})$. ``Discrimination (cum.)'' is the loss on cumulative
           goodness (the term of Thm.~3.1). Term gradients sum to the total gradient up to a relative
           error below $3{{\times}}10^{{-4}}$ at block~0 and ${{\le}}10^{{-6}}$ at blocks 1--3. MGC was trained
           with SAM, the two gated arms without.}}
  \label{{tab:gradshare}}
  \centering
  \small
  \setlength{{\tabcolsep}}{{3pt}}
  \begin{{tabular}}{{llcccc}}
    \toprule
    Arm & Term & Block 0 & Block 1 & Block 2 & Block 3 \\
    \midrule
""" + "\n".join("    " + r for r in rows) + r"""
    \bottomrule
  \end{tabular}
\end{table}
"""
    write("t_gradshare", ["gradient_share"], body)


# ============================================================================= C8/C9: frozen-backbone readouts
def t_readouts():
    s = J("s2ff_mgc")
    T, M, MA = s["trio_seed42"], s["mgc_per_seed"]["42"], s["mgc_agg"]
    order = [("goodness_sum_S1", "Goodness sum (deployed S1 rule)"),
             ("strict_ff_block_alone", "Strict-FF readout block alone"),
             ("strict_ff_plus_sum", "Strict-FF block $+$ frozen goodness"),
             ("ce_block_alone", "CE-trained block alone"),
             ("ce_plus_sum", "CE-trained block $+$ frozen goodness"),
             ("s2_attentive_probe", "Stage-2 attentive head (probe, not FF)")]
    rows = []
    for k, lab in order:
        rows.append(" & ".join([lab] + [f"{T[v][k]:.2f}" for v in ("gamma0", "gated_k0", "cumulative")]
                               + [f"{M[k]:.2f}", pm(MA[k])]) + " \\\\")
        if k == "ce_plus_sum":
            rows.append("\\midrule")
    mm = s["matched_seed42_mgc_minus_trio_strict_ff_alone_pp"]
    # Phase 6 (C8) caption fix: 'at most 0.27 pp' holds for the three original seed-42 backbones only;
    # on the MGC seed-42 backbone CE moves the block by 0.40 pp (computed from the same JSON).
    ce_d = s["ce_minus_strict_ff_block_alone_pp"]
    ce_trio_max = max(abs(ce_d[v]) for v in ("gamma0", "gated_k0", "cumulative"))
    ce_mgc42 = M["ce_block_alone"] - M["strict_ff_block_alone"]
    body = rf"""\begin{{table}}[!htb]
  \caption{{\textbf{{Frozen-backbone readouts}} (CIFAR-100 L4/D256, single crop, full 10k test, top-1 \%).
           All readout blocks see the frozen Stage-1 backbone only; the Stage-2 attentive head is a
           representation probe, not part of the FF method. Seed-42 columns are matched; the 3-seed
           MGC column is compared only with itself. On matched seed~42 the strict-FF block on the MGC
           backbone is {sg(mm['cumulative'])}/{sg(mm['gated_k0'])}/{sg(mm['gamma0'])}\,pp above cumulative/$\kappa{{=}}0$/$\gamma{{=}}0$,
           and the gap closes once frozen-block goodness is added (span {num(s['seed42_strict_ff_plus_sum_span_pp'])}\,pp).
           Cross-entropy training moves the block by at most {num(ce_trio_max)}\,pp on the three original
           seed-42 backbones, by {num(ce_mgc42)}\,pp on the MGC seed-42 backbone, and by {num(ce_d['mgc_mean'])}\,pp
           for the MGC 3-seed means.
           Goodness-sum row: logged S1 (the readout runs reproduce it within {num(s['S1_logged_vs_readout_recompute_max_abs_diff_pp'])}\,pp).}}
  \label{{tab:readouts}}
  \centering
  \small
  \setlength{{\tabcolsep}}{{3pt}}
  \resizebox{{\textwidth}}{{!}}{{%
  \begin{{tabular}}{{lccccc}}
    \toprule
    Readout on frozen backbone & $\gamma{{=}}0$ (s42) & $\kappa{{=}}0$ (s42) & Cum.\ (s42) & MGC (s42) & MGC (3 seeds) \\
    \midrule
""" + "\n".join("    " + r for r in rows) + r"""
    \bottomrule
  \end{tabular}%
  }
\end{table}
"""
    write("t_readouts", ["s2ff_mgc"], body)


# ============================================================================= C10: probes
def t_probes():
    p, trio = J("probes"), J("c100_trio")
    P = p["panels"]
    V = ("gamma0", "gated_k0", "cumulative")
    rows = []

    def anchor(label, prot):
        ag = {v: trio["variants"][v]["agg"][prot] for v in V}
        span = max(a["mean"] for a in ag.values()) - min(a["mean"] for a in ag.values())
        return " & ".join([label] + [pm(ag[v]) for v in V] + [num(span)]) + " \\\\"

    def prow(key, label):
        pv = P[key]["per_variant"]
        return " & ".join([label] + [pm(pv[v]) for v in V] + [num(P[key]["trio_span_pp"])]) + " \\\\"

    rows.append(anchor("Goodness sum (S1, deployed)", "S1"))
    rows.append(anchor("Stage-2 attentive probe (S2)", "S2"))
    rows.append("\\midrule")
    rows.append("\\multicolumn{5}{l}{\\emph{400-D goodness, block-softmax normalized}} \\\\")
    rows.append(prow("ridge_goodness_blocksoftmax", "\\quad ridge"))
    rows.append(prow("logistic_goodness_blocksoftmax", "\\quad logistic"))
    rows.append(prow("knn10cos_goodness_blocksoftmax", "\\quad 10-NN (cosine)"))
    rows.append("\\multicolumn{5}{l}{\\emph{400-D goodness, raw}} \\\\")
    rows.append(prow("logistic_goodness_flat", "\\quad logistic"))
    rows.append(prow("knn10cos_goodness_flat", "\\quad 10-NN (cosine)"))
    rows.append("\\multicolumn{5}{l}{\\emph{Block-3 goodness only (100-D)}} \\\\")
    rows.append(prow("logistic_goodness_block3", "\\quad logistic"))
    rows.append(prow("knn10cos_goodness_block3", "\\quad 10-NN (cosine)"))
    rows.append("\\multicolumn{5}{l}{\\emph{Pooled embedding, all blocks (mean label token)}} \\\\")
    rows.append(prow("logistic_pooled_meanemb_concat", "\\quad logistic"))
    rows.append(prow("knn10cos_pooled_meanemb_concat", "\\quad 10-NN (cosine)"))
    rows.append("\\multicolumn{5}{l}{\\emph{Pooled embedding, block 3 (mean label token)}} \\\\")
    rows.append(prow("logistic_pooled_meanemb_block3", "\\quad logistic"))
    rows.append(prow("knn10cos_pooled_meanemb_block3", "\\quad 10-NN (cosine)"))
    z = {k: num(P[k]["trio_span_pp"]) for k in ("logistic_pooled_zerotok_concat", "knn10cos_pooled_zerotok_concat",
                                                  "logistic_pooled_zerotok_block3", "knn10cos_pooled_zerotok_block3")}
    body = rf"""\begin{{table}}[!htb]
  \caption{{\textbf{{Label-free probes on the frozen CIFAR-100 trio}} (fit on each run's own 5k validation
           split, evaluated once on the full 10k test; top-1 \%, mean $\pm$ sample SD over 3 seeds; span =
           max $-$ min of the unrounded variant means). Structured readouts of the goodness scores keep the
           trio within 1\,pp; k-NN stability depends on per-block normalization, and block-3-only and
           pooled-embedding probes are bounded exceptions where the span exceeds 1\,pp. With a zero label
           token the pooled spans are {z['logistic_pooled_zerotok_concat']}/{z['knn10cos_pooled_zerotok_concat']}\,pp (all blocks,
           logistic/10-NN) and {z['logistic_pooled_zerotok_block3']}/{z['knn10cos_pooled_zerotok_block3']}\,pp (block~3).}}
  \label{{tab:probes}}
  \centering
  \small
  \setlength{{\tabcolsep}}{{3pt}}
  \begin{{tabular}}{{lcccc}}
    \toprule
    Readout / probe & $\gamma{{=}}0$ & $\kappa{{=}}0$ & Cumulative & Span (pp) \\
    \midrule
""" + "\n".join("    " + r for r in rows) + r"""
    \bottomrule
  \end{tabular}
\end{table}
"""
    write("t_probes", ["probes", "c100_trio"], body)


# ============================================================================= C11: readout ladder
def t_ladder():
    L = J("readout_ladder")
    V = ("gamma0", "gated_k0", "cumulative")
    PV = L["per_variant"]
    labels = {"R0": "R0: plain goodness sum (deployed)",
              "R1": "R1: per-depth weights $w_d$",
              "R2": "R2: per-depth temperatures ($w_d{>}0$)",
              "R3": "R3: margin-gated $w_d(x)$"}
    rows = []
    for R in ("R0", "R1", "R2", "R3"):
        cells = [labels[R]]
        for v in V:
            a = PV[v]["eval_acc_pp"][R]
            c = pm(a)
            if R != "R0":
                gnn = PV[v]["gain_vs_R0_pp"][R]
                c += f" (${gnn['mean']:+.2f}\\!\\pm\\!{gnn['sd']:.2f}$)"
            cells.append(c)
        cells.append(num(L["trio_span_pp_per_rung"][R]))
        rows.append(" & ".join(cells) + " \\\\")
    dg = L["differential_gain_R1"]
    rows.append("\\midrule")
    rows.append(" & ".join(["R1 gain minus cumulative's R1 gain [95\\% CI]",
                            ci({"delta_pp": dg["gamma0_minus_cumulative"]["diff_pp"], "ci95_pp": dg["gamma0_minus_cumulative"]["ci95_pp"]}),
                            ci({"delta_pp": dg["gated_k0_minus_cumulative"]["diff_pp"], "ci95_pp": dg["gated_k0_minus_cumulative"]["ci95_pp"]}),
                            "---", ""]) + " \\\\")
    body = rf"""\begin{{table}}[!htb]
  \caption{{\textbf{{Validation-fitted readout ladder on the frozen CIFAR-100 trio}} (exploratory and
           checkpoint-conditional). Each readout is fit on the run's own 5k validation split and evaluated
           once on the full 10k test (S1 single crop, EMA weights); top-1 \%, mean $\pm$ sample SD over
           3 seeds, in parentheses the gain over R0. R2 equals R1 restricted to positive weights, so the
           two coincide whenever the fitted R1 weights are positive. The trio span stays at most
           {num(max(L['trio_span_pp_per_rung'].values()))}\,pp at every rung, while the learned weights help the
           $\gamma{{=}}0$ and $\kappa{{=}}0$ variants more than the cumulative one (last row: paired 5000-resample
           bootstrap over the test set).
           R0 is recomputed from the dumped scores and matches the logged S1 within {num(L['R0_vs_logged_S1_max_abs_diff_pp'])}\,pp.}}
  \label{{tab:readout_ladder}}
  \centering
  \small
  \setlength{{\tabcolsep}}{{3pt}}
  \resizebox{{\textwidth}}{{!}}{{%
  \begin{{tabular}}{{lcccc}}
    \toprule
    Readout & $\gamma{{=}}0$ & $\kappa{{=}}0$ & Cumulative & Span (pp) \\
    \midrule
""" + "\n".join("    " + r for r in rows) + r"""
    \bottomrule
  \end{tabular}%
  }
\end{table}
"""
    write("t_ladder", ["readout_ladder"], body)


# ============================================================================= trio per-seed paired deltas (App. B.7)
def t_trio_perseed():
    """Verifier round (F16): Table 3 prints pooled paired CIs; the per-seed paired deltas of the trio
    pairs live here (MGC's per-seed deltas are in tab:mgc_full)."""
    tp = J("c100_trio_paired")
    pairs = (("gamma0_minus_cumulative", "$\\gamma{=}0$ $-$ cumulative"),
             ("gated_k0_minus_cumulative", "$\\kappa{=}0$ $-$ cumulative"),
             ("gamma0_minus_gated_k0", "$\\gamma{=}0$ $-$ $\\kappa{=}0$"))
    rows, big = [], []
    for key, label in pairs:
        cells = [label]
        for p in PROT:
            ps = tp["pairs"][p][key]["per_seed"]
            cells.append("/".join(f"${ps[s]['delta_pp']:+.2f}$" for s in SEEDS))
            big += [(label, p, s, ps[s]["delta_pp"]) for s in SEEDS if abs(ps[s]["delta_pp"]) > 1.0]
        rows.append(" & ".join(cells) + " \\\\")
    assert all(tp["pairs"][p][k]["pooled"]["within_pm1pp"] for p in PROT for k, _ in pairs)
    assert len(big) == 1, big  # the caption sentence below names exactly one exceedance
    bl, bp, bs, bv = big[0]
    body = rf"""\begin{{table}}[!htb]
  \caption{{\textbf{{Per-seed paired differences of the CIFAR-100 trio}} (pp, seeds 42/123/456; each on the
           seed's full 10k test set). The pooled differences and their 5000-resample bootstrap CIs are in
           Table~\ref{{tab:dissociation_merged}} (vs.\ cumulative) and App.~\ref{{app:churn}}; every pooled CI of
           the three pairs lies inside $\pm1$\,pp under all four protocols, while one per-seed value exceeds
           1\,pp in magnitude ({bl}, {bp}, seed {bs}: ${bv:+.2f}$). MGC's per-seed differences are in
           Table~\ref{{tab:mgc_full}}.}}
  \label{{tab:trio_perseed}}
  \centering
  \small
  \setlength{{\tabcolsep}}{{3pt}}
  \resizebox{{\textwidth}}{{!}}{{%
  \begin{{tabular}}{{lcccc}}
    \toprule
    Pair & S1 & S1-TTA & S2 & S2-TTA \\
    \midrule
""" + "\n".join("    " + r for r in rows) + r"""
    \bottomrule
  \end{tabular}%
  }
\end{table}
"""
    write("t_trio_perseed", ["c100_trio_paired"], body)


# ============================================================================= C6: BP rows for Table 2
def t_bp_rows():
    b = J("bp_calibration")
    R = b["rows"]

    def mparams(key):
        return R[key]["per_seed"]["42"]["n_params_millions"]

    spec = [
        ("plain_cnn_bp", f"Plain CNN ({mparams('plain_cnn_bp'):.2f}\\,M, ch.\\ 64/128/256)", "BP", "strong"),
        ("plain_cnn_ff", f"Plain CNN ({mparams('plain_cnn_ff'):.2f}\\,M, ch.\\ 64/128/256)", "FF", "FF-pipeline"),
        ("bp_weak", f"FF backbone (stripped, {mparams('bp_weak'):.2f}\\,M)", "BP", "weak"),
        ("bp_strong", f"FF backbone (stripped, {mparams('bp_strong'):.2f}\\,M)", "BP", "BP-strong"),
    ]
    lines = ["% Rows for Table 2 (tab:bp_ff_ablation), columns: Architecture & Training & Aug. & Val Top-1 & Test no-TTA & Test TTA.",
             "% Usage: \\input{tables/t_bp_rows} before the table (it only defines a macro), then write \\BPRowsNThree",
             "% inside the tabular. (A bare \\input inside a tabular followed by \\bottomrule/\\midrule fails with 'Misplaced \\noalign'.)",
             "% All four rows are n=3 (seeds 42/123/456; mean +- sample SD). Per-seed test top-1:"]
    for key, *_ in spec:
        v = R[key]["test_top1"]["values"]
        lines.append(f"%   {key}: " + " / ".join(f"{x:.2f}" for x in v))
    lines.append(f"% Co-design gap (plain CNN BP - FF) = {b['co_design_gap_pp']:.2f} pp; augmentation effect (BP strong - weak) = {b['augmentation_effect_pp']:.2f} pp.")
    lines.append("\\providecommand{\\BPRowsNThree}{}")
    lines.append("\\renewcommand{\\BPRowsNThree}{%")
    for key, arch, tr, aug in spec:
        lines.append("  " + " & ".join([arch, tr, aug, pm(R[key]["val_top1"]), pm(R[key]["test_top1"]), "---"]) + " \\\\")
    lines.append("}")
    write("t_bp_rows", ["bp_calibration"], "\n".join(lines) + "\n")


# ============================================================================= E2: validation-selected early exit (C14)
def t_early_exit():
    """Family x selection rule: test delta vs. full depth, #runs with delta >= 0, FLOPs saved, chosen depths.
    Summaries come from analysis/early_exit.py (asserted equal to the selector's own family aggregates);
    repaired-vs-cumulative rows: CIFAR-10 descriptive (one seed per arm), CIFAR-100 paired by seed."""
    import early_exit as E
    e2 = J("e2_exit")
    S = E.summarize(e2)
    RL = E.RULES

    def z(v):  # exact-zero paired differences must not print as "-0.0"
        return 0.0 if abs(v) < 1e-9 else v

    def pmx(st, nd):
        return f"${z(st['mean']):+.{nd}f}\\!\\pm\\!{z(st['sd']):.{nd}f}$"

    def pmu(st, nd):
        return f"${st['mean']:.{nd}f}\\!\\pm\\!{z(st['sd']):.{nd}f}$"

    def group_row(label, g, listed=False):
        cells = [label]
        for r in RL:
            x = g[r]
            n = x["delta_pp"]["n"]
            if listed:   # two single-seed arms: print both values instead of a mean +- SD
                cells += [" / ".join(f"${v:+.2f}$" for v in x["delta_pp"]["values"]), f"{x['n_delta_ge_0']}/{n}",
                          " / ".join(f"${v:.1f}$" for v in x["saved_pct"]["values"])]
            else:
                cells += [pmx(x["delta_pp"], 2), f"{x['n_delta_ge_0']}/{n}", pmu(x["saved_pct"], 1)]
        return " & ".join(cells) + " \\\\"

    def paired_row(label, p):
        cells = [label]
        for r in RL:
            cells += [pmx(p[r]["delta_pp"], 2), "---", pmx(p[r]["saved_pp"], 1)]
        return " & ".join(cells) + " \\\\"

    def depth_row(g):
        cells = ["\\quad runs at $d{=}1/2/3/4$"]
        for r in RL[:2]:
            cells.append(f"\\multicolumn{{3}}{{c}}{{{'/'.join(str(k) for k in g[r]['runs_at_depth'])}}}")
        mb = g["D_dynamic_exit"]["mean_blocks"]
        cells.append(f"\\multicolumn{{3}}{{c}}{{mean blocks {mb['min']:.2f}--{mb['max']:.2f}}}")
        return " & ".join(cells) + " \\\\"

    c10cum = [E.C10_ARMS[n][1] for n in S["c10_cumulative"]["members"]]
    assert c10cum == [r"constant $\gamma{=}0.7$", r"LCFF $\gamma{=}1.0$"], c10cum
    n_rep = len(S["c10_repaired"]["members"])
    n_gated = sum(E.family_of(n) == "gated" for n in S["c10_repaired"]["members"])
    P = S["c100_paired"]
    rows = [
        "\\multicolumn{10}{@{}l}{\\emph{CIFAR-10 L4/D128, seed 42, no SAM}} \\\\",
        group_row(f"All {S['c10_all'][RL[0]]['delta_pp']['n']} arms", S["c10_all"]),
        group_row(f"\\quad cumulative ({len(c10cum)} arms)", S["c10_cumulative"], listed=True),
        group_row(f"\\quad repaired ({n_rep} arms)", S["c10_repaired"]),
        depth_row(S["c10_all"]),
        "\\midrule",
        "\\multicolumn{10}{@{}l}{\\emph{CIFAR-100 L4/D256 trio, seeds 42/123/456}} \\\\",
        group_row(f"All {S['c100_all'][RL[0]]['delta_pp']['n']} runs", S["c100_all"]),
        group_row("\\quad $\\gamma{=}0$ (history-free)", S["c100_gamma0"]),
        group_row("\\quad $\\kappa{=}0$ (gated)", S["c100_gated_k0"]),
        group_row("\\quad cumulative", S["c100_cumulative"]),
        paired_row("\\quad $\\gamma{=}0$ $-$ cum., paired", P["gamma0_minus_cumulative"]),
        paired_row("\\quad $\\kappa{=}0$ $-$ cum., paired", P["gated_k0_minus_cumulative"]),
        depth_row(S["c100_all"]),
    ]
    dep = S["flops_saved_pct_by_depth"]
    g = S["gates"]
    assert g["n_pass"] + g["n_pass_numerics"] == 18 and 2 <= g["max_test_delta_examples"] <= 3
    body = rf"""\begin{{table}}[!htb]
  \caption{{\textbf{{Validation-selected early exit}} (S1 single crop, EMA weights). Every operating point is chosen on the run's own 5k validation split and
           evaluated once on the 10k test split. \emph{{T}}: the shallowest depth whose validation accuracy is at least
           the full-depth value; \emph{{T$'$}}: the validation-best depth (ties to the shallower); \emph{{D}}: dynamic exit
           after block $d{{<}}L$ once the top-1 minus top-2 margin of the running class score exceeds a threshold, set to the
           value with the fewest mean validation blocks at no loss of validation accuracy. $\Delta$: test accuracy at the
           operating point minus full-depth test accuracy of the same checkpoint (pp); ${{\geq}}0$: runs with $\Delta{{\geq}}0$;
           Saved: FLOPs saved vs.\ full depth (\%; stem plus every label hypothesis's blocks; stopping after block~0 saves
           {dep['c10'][0]:.1f}\% on CIFAR-10 and {dep['c100'][0]:.1f}\% on CIFAR-100). Mean $\pm$ sample SD over runs (on CIFAR-10, over nine
           configurations at one seed). CIFAR-10 cumulative arms: constant $\gamma{{=}}0.7$ / LCFF $\gamma{{=}}1.0$, listed
           individually; repaired arms: $\gamma{{=}}0$ and the {dict(enumerate(['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven']))[n_gated]} hardness-gated arms. \emph{{runs at $d{{=}}1/2/3/4$}}: how
           many runs select each depth (T, T$'$); D: range of mean test blocks. Paired rows: repaired minus cumulative of the same seed, mean
           $\pm$ SD over the three seeds, of $\Delta$ (pp) and of Saved (percentage points). Each re-scored checkpoint reproduces its logged full-depth S1
           test accuracy within one test image ({g['n_pass']} runs) or {['two', 'three'][g['max_test_delta_examples'] - 2]} images ({g['n_pass_numerics']} runs; TF32 training-time vs.\ FP32
           re-scoring numerics).}}
  \label{{tab:early_exit}}
  \centering
  \small
  \setlength{{\tabcolsep}}{{3pt}}
  \resizebox{{\textwidth}}{{!}}{{%
  \begin{{tabular}}{{lccccccccc}}
    \toprule
    & \multicolumn{{3}}{{c}}{{T}} & \multicolumn{{3}}{{c}}{{T$'$}} & \multicolumn{{3}}{{c}}{{D (dynamic exit)}} \\
    \cmidrule(lr){{2-4}} \cmidrule(lr){{5-7}} \cmidrule(lr){{8-10}}
    Runs & $\Delta$ (pp) & ${{\geq}}0$ & Saved (\%) & $\Delta$ (pp) & ${{\geq}}0$ & Saved (\%) & $\Delta$ (pp) & ${{\geq}}0$ & Saved (\%) \\
    \midrule
""" + "\n".join("    " + r for r in rows) + r"""
    \bottomrule
  \end{tabular}%
  }
\end{table}
"""
    write("t_early_exit", ["e2_exit"], body)


# ============================================================================= E1: aligned-checkpoint separation (A11)
def t_e1_aligned():
    """Per-seed deepest-block sep at the validation-selected checkpoints, two measurements side by side:
    tier 1 = logged training-time value at the checkpoint epoch (19 points, e1_tier1_sep_acc.json);
    tier 2 = recomputed on the stage1_best EMA checkpoint in eval mode (18 points, e1_sep_tier2.json; the
    published C10 gamma=0 seed-42 checkpoint is lost). The two use different weights/mode/negatives, so the
    caption tells the reader to compare within a column only. The correlations are quoted in the
    fig:accuracy_vs_ratio caption (hand-typed there, verified against the same JSONs)."""
    t1, t2 = J("e1_tier1_sep_acc"), J("e1_sep_tier2")
    assert t1["gates"]["all_passed"] and not t2["_header"]["missing_or_failed"]
    t1p = {}
    for p in t1["points"]:
        t1p.setdefault(p["config"], []).append(p)
    t2p = {(p["config"], p["seed"]): p for p in t2["points"]}
    # (label, tier-1 config, {seed: tier-2 config or None}, {seed: run_cfg assertions}, {seed: footnote mark})
    tri = {s: "c100_d256_%s" for s in (42, 123, 456)}
    spec = [
        (r"CIFAR-10 L4/D256 $\gamma{=}0$", "c10_gamma0", {42: None, 123: "c10_d256_gamma0", 456: "c10_d256_gamma0"},
         {42: dict(block_curr_lambda=0.0, depth_order_lambda=0.0, gamma_scale=0.0),
          123: dict(block_curr_lambda=0.25, depth_order_lambda=0.2, gamma_scale=0.0),
          456: dict(block_curr_lambda=0.25, depth_order_lambda=0.2, gamma_scale=0.0)}, {42: "a"}),
        (r"CIFAR-10 L4/D256 \textsc{cp-fair}", "c10_cp_fair", {s: "c10_d256_cp_fair" for s in (42, 123, 456, 789)},
         {}, {}),
        (r"CIFAR-10 L4/D128 gated $\kappa{=}0$", "gated_l4d128_k0",
         {42: "c10_d128_gated_k0_samoff", 123: "c10_d128_gated_k0_samon", 456: "c10_d128_gated_k0_samon"},
         {42: dict(use_sam=False), 123: dict(use_sam=True), 456: dict(use_sam=True)}, {42: "b"}),
        None,
        (r"CIFAR-100 L4/D256 $\gamma{=}0$", "c100_gamma0", {s: v % "gamma0" for s, v in tri.items()}, {}, {}),
        (r"CIFAR-100 L4/D256 gated $\kappa{=}0$", "c100_gated_k0", {s: v % "gated_k0" for s, v in tri.items()}, {}, {}),
        (r"CIFAR-100 L4/D256 cumulative", "c100_cumulative", {s: v % "cumulative" for s, v in tri.items()}, {}, {}),
    ]
    assert sorted(x[1] for x in spec if x) == sorted(t1p), sorted(t1p)
    assert sorted((c, s) for x in spec if x for s, c in x[2].items() if c) == sorted(t2p), sorted(t2p)
    rows, n_hi, n_t2 = [], 0, 0
    for x in spec:
        if x is None:
            rows.append("\\midrule")
            continue
        label, c1, c2s, want, mark = x
        if rows and rows[-1] != "\\midrule":
            rows.append("\\addlinespace")
        a = sorted(t1p[c1], key=lambda p: p["seed"])
        assert [p["seed"] for p in a] == sorted(c2s), (c1, [p["seed"] for p in a])
        for i, p in enumerate(a):
            s = p["seed"]
            for k, v in want.get(s, {}).items():
                assert p["run_cfg"][k] == v, (c1, s, k, p["run_cfg"][k])
            logged = f"{p['sep_deep_at_best_epoch']:.2f}"
            if c2s[s] is None:
                rec = "---"
            else:
                q = t2p[(c2s[s], s)]   # tier 2 is read at the same checkpoint epoch and quotes the same accuracies
                assert q["epoch_stage1"] == p["stage1_best_epoch"]
                assert abs(q["sep_tier1_logged_at_ckpt_epoch"] - p["sep_deep_at_best_epoch"]) < 1e-9
                for prot in ("S2-TTA", "S1"):
                    assert abs(100 * q["acc"][prot] - p["acc_test_pct"][prot]) < 1e-6
                n_hi += q["sep_tier2"] > q["sep_tier1_logged_at_ckpt_epoch"]
                n_t2 += 1
                rec = f"{q['sep_tier2']:.2f}"
            seed = f"{s}$^{{\\mathrm{{{mark[s]}}}}}$" if s in mark else str(s)
            rows.append(" & ".join([label if i == 0 else "", seed, logged, rec,
                                    f"{p['acc_test_pct']['S2-TTA']:.2f}", f"{p['acc_test_pct']['S1']:.2f}"]) + " \\\\")
    assert n_t2 == t2["_header"]["n_points"] == 18 and len(t1["points"]) == 19
    # measurement details, all read from the tier-2 JSON
    P2 = t2["points"]
    assert len({p["n_batches"] for p in P2}) == 1 and len({p["data_seed"] for p in P2}) == 1
    n_batches = P2[0]["n_batches"]
    ex = {ds: sorted({p["n_batches"] * p["batch_size"] for p in P2 if p["dataset"] == ds}) for ds in ("cifar10", "cifar100")}
    assert all(len(v) == 1 for v in ex.values()), ex
    se_max = max(p["sep_tier2_se"] for p in P2)
    d_img = [round(abs(p["gate"]["recomputed"] - p["gate"]["anchor"]) * 10000) for p in P2]
    assert all((d <= 1) == p["gate"]["strict"] for d, p in zip(d_img, P2)) and max(d_img) == 2
    n_strict, n_fb = sum(d <= 1 for d in d_img), sum(d == 2 for d in d_img)
    cv = t2["code_validation_mgc_d128_seed42"]["raw_train"]
    assert cv["vs_gradshare"]["pass_"]
    words = dict(enumerate(["zero", "one", "two", "three", "four", "five"]))
    body = rf"""\begin{{table}}[!htb]
  \caption{{\textbf{{Deepest-block separation at the validation-selected checkpoints}} (exploratory; per-seed
           analysis of Fig.~\ref{{fig:accuracy_vs_ratio}}).
           \emph{{Logged}}: $\text{{sep}}^\text{{cur}}_\text{{nl}}$ of the deepest block as logged during training in the
           epoch of the selected Stage-1 checkpoint (training mode, raw weights, epoch mean).
           \emph{{Recomputed}}: the same quantity recomputed on that checkpoint's EMA weights in eval mode through the
           trainer's own diagnostic code (hard negatives mined by the EMA teacher; {n_batches} consecutive training batches
           drawn with a fixed seed, i.e.\ {ex['cifar10'][0]:,} images on CIFAR-10 and {ex['cifar100'][0]:,} on CIFAR-100; standard
           error over batches ${{\leq}}{se_max:.2f}$). The two measurements differ in weights, mode, and negatives (the recomputed value
           is higher at {n_hi} of {n_t2} points), so compare values within a column only. Accuracies are test top-1 of the
           same checkpoints (S2~TTA: trained head on the frozen EMA backbone, flip TTA; S1: EMA backbone, single crop).
           $^\mathrm{{a}}$Trained with $\lambda_\text{{curr}}{{=}}\lambda_\text{{depth}}{{=}}0$ (seeds 123/456: $0.25$/$0.2$); its
           published checkpoint is no longer available, so the recomputation covers {n_t2} of the {len(t1['points'])} points.
           $^\mathrm{{b}}$Trained without SAM (seeds 123/456 with SAM); a separate configuration in the recomputed analysis.
           Each recomputed checkpoint reproduces its logged S1 test accuracy within one test image ({n_strict} points)
           or {words[max(d_img)]} images ({n_fb} points; TF32 training-time vs.\ FP32 recomputation numerics). As a code check, on the
           CIFAR-10 L4/D128 MGC seed-42 checkpoint in training mode the code gives {cv['deepest_sep_curr_nl']:.2f}, against
           {cv['vs_gradshare']['gradshare_block3_margin_curr_nl']:.2f} from the independent gradient-share measurement
           (App.~\ref{{app:gradshare}}).}}
  \label{{tab:e1_aligned}}
  \centering
  \footnotesize
  \begin{{tabular}}{{llcccc}}
    \toprule
    & & \multicolumn{{2}}{{c}}{{Deepest-block $\text{{sep}}^\text{{cur}}_\text{{nl}}$}} & \multicolumn{{2}}{{c}}{{Test top-1 (\%)}} \\
    \cmidrule(lr){{3-4}} \cmidrule(lr){{5-6}}
    Configuration & Seed & Logged & Recomputed & S2~TTA & S1 \\
    \midrule
""" + "\n".join("    " + r for r in rows) + r"""
    \bottomrule
  \end{tabular}
\end{table}
"""
    write("t_e1_aligned", ["e1_tier1_sep_acc", "e1_sep_tier2"], body)


# ============================================================================= F1: MGC block-0 / auxiliary control
def t_f1_control():
    """F1 (experiments/f1_mgc_block0): arms a/b/c + the MGC-D128 runs, CIFAR-10 L4/D128, SAM on, n = 3 each.
    Accuracy deltas = pooled example-level paired bootstrap (results/f1_block0_control.json contrasts.*);
    sep deltas = mean +- sample SD of the seed-paired differences. Registered predictions are scored in the
    JSON (P2 fails); the caption states every verdict from the JSON, never hand-typed."""
    f = J("f1_block0_control")
    assert f["all_gates_pass"]
    A_, K, P = f["arms"], f["contrasts"], f["predictions"]
    hw_code = {"GB10": "G", "A100": "A"}

    def gpu(arm):
        return "/".join(hw_code[A_[arm]["hardware_by_seed"][str(s)]] for s in SEEDS)

    def arm_row(label, arm):
        a = A_[arm]["agg"]
        return " & ".join([label, pm(a["sep_curr_nl_deepest"])] + [pm(a[p]) for p in PROT]) + " \\\\"

    def d_row(label, key):
        k = K[key]
        sd = k["seed_paired_differences"]["sep_deepest"]
        sep = f"${sd['mean']:+.2f}\\!\\pm\\!{sd['sd']:.2f}$"
        return " & ".join([f"\\quad $\\Delta$ vs.\\ {label}", sep]
                          + [ci(k["example_level_paired_bootstrap"][p]["pooled"]) for p in PROT]) + " \\\\"

    rows = [
        arm_row("(a) Cumulative + aux.", "a"),
        arm_row("(b) Cumulative, no aux.", "b"),
        d_row("(a)", "b_minus_a"),
        d_row("MGC", "b_minus_mgc"),
        arm_row("(c) MGC + block-0 aux.", "c"),
        d_row("(a)", "c_minus_a"),
        d_row("MGC", "c_minus_mgc"),
        arm_row("MGC", "mgc"),
        d_row("(a)", "mgc_minus_a"),
    ]
    # every accuracy CI of every contrast lies inside +-1 pp (asserted: the caption says so)
    allin = all(K[k]["example_level_paired_bootstrap"][p]["pooled"]["within_pm1pp"] for k in K for p in PROT)
    assert allin
    dec = f["deepest_sep_decomposition"]
    m = dec["mean"]
    p1, p2, p3, p4 = (P[k] for k in ("P1", "P2", "P3", "P4"))
    assert (p1["verdict"], p2["verdict"], p3["verdict"], p4["verdict"]) == ("PASS", "FAIL", "PASS", "PASS"), \
        "caption wording assumes P1/P3/P4 pass and P2 fails"
    assert p2["clause_mean_below_4.72"] == "FAIL" and p2["clause_every_seed_below_lowest_mgc_seed"] == "PASS"
    b1, b2 = p1["band_registered"]
    # registered thresholds, as printed in the statements scored by analysis/f1_analysis.py
    assert "< 4.72" in p2["statement"] and "(5.21)" in p2["statement"] and "< 4.72" in p4["statement"]
    assert "[86.27, 88.27] (87.27 +/- 1 pp)" in p3["statement"]
    sd_s2tta = [K[k]["seed_paired_differences"]["S2-TTA"]["sd"] for k in ("c_minus_mgc", "b_minus_mgc")]
    decomp = (f"MGC's deepest-block gain over (a), ${m['gain_mgc_minus_a']:.2f}$, splits into "
              f"${m['aux_removal_b_minus_a']:.2f}$ from removing the auxiliary ((b)$-$(a), "
              f"{100 * m['aux_removal_share_of_mean_gain']:.0f}\\%) and ${m['compensation_mgc_minus_b']:.2f}$ "
              f"from the compensator (MGC$-$(b), {100 * m['compensation_share_of_mean_gain']:.0f}\\%)")
    gpus = "; ".join(f"{lab} {gpu(arm)}" for lab, arm in (("(a)", "a"), ("(b)", "b"), ("(c)", "c"), ("MGC", "mgc")))
    body = rf"""\begin{{table}}[!htb]
  \caption{{\textbf{{MGC control at CIFAR-10 L4/D128}} (constant $\gamma{{=}}0.7$, SAM on, 180+10 epochs, seeds
           42/123/456 per arm; mean $\pm$ sample SD, $n{{=}}3$). Aux.: the depth-scaled current-block auxiliary
           ($0.25$ at block~0, $0.50$/$0.75$/$1.00$ at blocks 1--3; residual-weighted at blocks 1--3 only). (a) keeps it at
           every block; (b) removes it at every block, with no compensator; MGC (Tab.~\ref{{tab:mgc_full}})
           replaces it by the compensator at blocks 1--3 and has none at block~0; (c) is MGC with block~0's
           auxiliary kept. sep: $\text{{sep}}^\text{{cur}}_\text{{nl}}$ at block~3, last Stage-1 epoch. $\Delta$
           rows: for sep, mean $\pm$ SD of the seed-paired differences; for accuracy, the paired difference
           pooled over the three seeds ($n{{=}}30{{,}}000$ test predictions) with a 5000-resample bootstrap 95\%
           CI that resamples test images only, so it omits seed-to-seed variation (SD of the per-seed S2-TTA
           differences of (c) and (b) vs.\ MGC: {sd_s2tta[0]:.2f} and {sd_s2tta[1]:.2f}\,pp). Every CI lies inside
           $\pm1$\,pp. {decomp}. GPU per seed (G, NVIDIA GB10 on a DGX Spark; A, Colab A100): {gpus}; the
           arms thus mix hardware and software stacks, and (b)$-$(a) is fully confounded with them. No run
           was resumed. Registered before the runs: P1, (c) in $[{b1:.2f}, {b2:.2f}]$: passes; P2, (b) below
           $4.72$ with every (b) seed below the lowest MGC seed ($5.21$): \textbf{{fails}} ((b) is
           ${p2['b_mean']:.2f}$; the second clause holds); P3, every arm's S2-TTA within 1\,pp of MGC's $87.27$:
           passes; P4, (a) below $4.72$: passes.}}
  \label{{tab:f1_control}}
  \centering
  \footnotesize
  \setlength{{\tabcolsep}}{{3pt}}
  \resizebox{{\textwidth}}{{!}}{{%
  \begin{{tabular}}{{lccccc}}
    \toprule
    Arm & sep (L3) & S1 & S1-TTA & S2 & S2-TTA \\
    \midrule
""" + "\n".join("    " + r for r in rows) + r"""
    \bottomrule
  \end{tabular}%
  }
\end{table}
"""
    write("t_f1_control", ["f1_block0_control"], body)


# ============================================================================= F2: gamma=0 multi-seed table
def t_gamma0_multiseed():
    """CIFAR-10 L4/D256 gamma = 0 per seed (App. B multi-seed tables), from results/f2_gamma0_s42.json:
    published seed 42 (lambda_curr = lambda_depth = 0), the F2 matched-config rerun of seed 42, seeds 123/456,
    the published n = 3 (kept as the headline) and the matched n = 3 next to it. sep = deepest-block
    sep_curr_nl at the last Stage-1 epoch (362; F2's registered P2 metric) and at the validation-selected
    epoch (the convention of tab:e1_aligned)."""
    f = J("f2_gamma0_s42")
    assert f["gates"]["all_passed"]
    R, F2 = f["references"], f["f2_run"]
    ag = f["aggregates"]
    pr = f["predictions"]
    assert all(pr[k]["result"] == "PASS" for k in ("P1", "P1b", "P2")), "note wording assumes P1/P1b/P2 pass"
    cmp_pub = f["comparison_vs_published_seed42"]
    gpu = {"A100": "A100", "GB10": "GB10"}

    def dev(r):
        d = r["env"]["device0"]
        return "A100" if "A100" in d else ("GB10" if "GB10" in d else d)

    def seed_row(label, r, lam):
        acc = [f"{r['acc_pct'][p]:.2f}\\%" for p in PROT]
        return " & ".join([label, lam, gpu[dev(r)]] + acc
                          + [num(r["sep_deep_last"]), f"{r['sep_deep_selected']:.2f} ({r['stage1_selected_epoch']})"]) + " \\\\"

    def agg_row(label, a, lam, sep=True):
        cells = [label, lam, "mixed"] + [f"${a[p]['mean']:.2f} \\pm {a[p]['sd_sample']:.2f}$" for p in PROT]
        if sep:
            cells += [f"${a['sep_last_epoch_362']['mean']:.2f} \\pm {a['sep_last_epoch_362']['sd_sample']:.2f}$",
                      f"${a['sep_selected_epoch']['mean']:.2f} \\pm {a['sep_selected_epoch']['sd_sample']:.2f}$"]
        else:
            cells += ["---", "---"]
        return " & ".join(cells) + " \\\\"

    # the published seed 42 ran on an A100, seeds 123/456 on the GB10 (asserted: the note says so)
    assert dev(R["pub42"]) == "A100" and dev(F2) == "A100" and dev(R["s123"]) == dev(R["s456"]) == "GB10"
    rows = [
        seed_row("42 (published)", R["pub42"], "0 / 0"),
        seed_row("42 (rerun)$^\\ast$", F2, "0.25 / 0.2"),
        seed_row("123", R["s123"], "0.25 / 0.2"),
        seed_row("456", R["s456"], "0.25 / 0.2"),
        "\\midrule",
        agg_row("Published $n{=}3$ (42, 123, 456)", ag["published_n3"], "mixed", sep=False),
        agg_row("Matched $n{=}3$ (42 rerun, 123, 456)", ag["matched_config_n3"], "0.25 / 0.2"),
    ]
    dl = [cmp_pub["protocols_pp"][p]["delta_new_minus_published"] for p in PROT]
    pmin = min(cmp_pub["paired_test_predictions"][p]["exact_mcnemar_p_two_sided"] for p in PROT)
    ts = f["sep_trajectory_summary"]
    lo, hi = ts["new42_minus_s123_456_mean_range"]
    segr = F2["segment_stage1_epoch_ranges"]
    assert R["s123"]["stage1_selected_epoch"] == R["s456"]["stage1_selected_epoch"]
    sel_other = R["s123"]["stage1_selected_epoch"]
    assert [list(x) for x in segr] == [[1, 3], [4, 274], [275, 362]], segr
    # registered qualifiers the note must carry (f2_gamma0_s42.json predictions.registered_outcome_branch)
    rob = pr["registered_outcome_branch"]
    assert any("one re-run of one seed" in q and "does not separate block_curr_lambda from depth_order_lambda" in q
               for q in rob["required_qualifiers"])
    assert "trainer code identity is verified only through config.json" in rob["scope_note"]
    torch_pub, torch_new = (".".join(r["env"]["torch"].split("+")[0].split(".")[:2]) for r in (R["pub42"], F2))
    assert (torch_pub, torch_new) == ("2.10", "2.11"), (torch_pub, torch_new)
    body = rf"""\begin{{table}}[h]
  \caption{{Multi-seed stability of $\gamma{{=}}0$ (history-free). All runs share the architecture, optimizer
           (SAM + AdamW) and schedule (L4, D256, 32 experts top-4, bs512, 362+20 epochs), but the published
           seed~42 used $\lambda_\text{{curr}}{{=}}\lambda_\text{{depth}}{{=}}0$, whereas seeds 123 and 456 used
           $\lambda_\text{{curr}}{{=}}0.25$ and $\lambda_\text{{depth}}{{=}}0.2$ (all other settings are identical),
           so the published $n{{=}}3$ pools two configurations; it remains the headline.
           $^\ast$Seed~42 rerun in the seed-123/456 configuration; the matched $n{{=}}3$ is reported next to
           the published one. All accuracies come from each run's final official-test evaluation. sep:
           deepest-block $\text{{sep}}^\text{{cur}}_\text{{nl}}$ at the last Stage-1 epoch and at the
           validation-selected epoch (in parentheses; as in App.~Tab.~\ref{{tab:e1_aligned}}). GPU: Colab A100 or DGX Spark GB10, so both $n{{=}}3$
           SDs mix seed and hardware variation.}}
  \label{{tab:gamma0_multiseed}}
  \centering
  \small
  \setlength{{\tabcolsep}}{{3pt}}
  \resizebox{{\textwidth}}{{!}}{{%
  \begin{{tabular}}{{lcccccccc}}
    \toprule
    Seed & $\lambda_\text{{curr}}$ / $\lambda_\text{{depth}}$ & GPU & S1 (no-TTA) & S1 (TTA) & S2 (no-TTA) & S2 (TTA) & sep (last) & sep (sel.) \\
    \midrule
""" + "\n".join("    " + r for r in rows) + rf"""
    \bottomrule
  \end{{tabular}}%
  }}

  \vspace{{1ex}}
  \begin{{flushleft}}\footnotesize
  Because the configurations differ, the separation gap between the published seed~42 and seeds 123/456
  should not be read as seed-to-seed variance. The rerun (one seed) supports this: in the seed-123/456
  configuration, seed~42 reaches ${F2['sep_deep_last']:.2f}$ at the last epoch (published:
  ${R['pub42']['sep_deep_last']:.2f}$), while its accuracy moves by ${min(dl):+.2f}$ to ${max(dl):+.2f}$\,pp
  (paired exact McNemar $p{{\ge}}{pmin:.2f}$). It does not separate $\lambda_\text{{curr}}$ from
  $\lambda_\text{{depth}}$, and the published run used an older software stack (PyTorch {torch_pub} vs.\
  {torch_new}) and trainer, checked only through its configuration file. Registered before the rerun,
  S1~TTA within the seed-123/456 range $[91.10, 91.40]$ (by one test image), S1~TTA within $\pm0.30$\,pp
  of their mean, and a last-epoch separation in $[6.9, 8.9]$ all pass. At its validation-selected epoch
  ({F2['stage1_selected_epoch']}, vs.\ {sel_other} for seeds 123/456; separation was still rising) the rerun's separation is
  ${F2['sep_deep_selected']:.2f}$, close to the published run's ${R['pub42']['sep_deep_selected']:.2f}$; at the common
  evaluation epochs from {F2['stage1_selected_epoch']} on it lies ${lo:.2f}$ to ${hi:+.2f}$ from the seed-123/456 mean.
  The rerun trained on a Colab A100 in three segments (Stage-1 epochs {segr[0][0]}--{segr[0][1]}, {segr[1][0]}--{segr[1][1]},
  and {segr[2][0]}--{segr[2][1]} plus Stage~2; an earlier attempt ended before its first epoch) with two resumes
  that restored the random-number state but re-seeded the data-loader workers, so it is not bitwise
  equal to an uninterrupted run; epoch~4 was trained twice (the second segment resumed from the epoch-3 checkpoint).
  Seed~42's Stage-2 values come from its run log (correction: App.~\ref{{app:changes}}, item B4).
  \end{{flushleft}}
\end{{table}}
"""
    write("t_gamma0_multiseed", ["f2_gamma0_s42"], body)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    t_dissociation_merged()
    t_mgc()
    t_hinge()
    t_gradshare()
    t_readouts()
    t_probes()
    t_ladder()
    t_trio_perseed()
    t_bp_rows()
    t_early_exit()
    t_e1_aligned()
    t_f1_control()
    t_gamma0_multiseed()


if __name__ == "__main__":
    main()
