#!/usr/bin/env python3
"""Generate the camera-ready LaTeX tables from results/*.json. Never hand-type numbers.

Run:  python analysis/make_tables.py        (from CR; writes paper/tables/*.tex)

Every file starts with a provenance line naming its source JSONs. Conventions:
  * mean +- SAMPLE SD over seeds (ddof=1), 2 dp unless stated;
  * paired deltas / CIs come from the 5000-resample paired bootstraps in results/;
  * in the merged dissociation table the Range row is computed from the UNROUNDED means
    (verifier fix: the submitted Table 3 used the printed 2-dp means, which gave an S2-TTA
    range of 0.27 pp instead of 0.28 pp); probe / ladder spans are of unrounded means too.
Tables use booktabs only.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import config as C  # noqa: E402

PROT = list(C.PROTOCOLS)
SEEDS = [str(s) for s in C.SEEDS]
OUT = C.TABLES


def J(name):
    return json.load(open(C.RESULTS / f"{name}.json"))


def header(sources):
    srcs = ", ".join(f"results/{s}.json" for s in sources)
    return f"% AUTO-GENERATED by analysis/make_tables.py from {srcs} — do not hand-edit\n"


def write(name, sources, body):
    p = OUT / f"{name}.tex"
    with open(p, "w") as f:
        f.write(header(sources))
        f.write(body.rstrip() + "\n")
    print(f"wrote paper/tables/{name}.tex")


# ----------------------------------------------------------------------------- formatting
def num(x, nd=2):
    return f"{x:.{nd}f}"


def pm(agg, nd=2, sdnd=None):
    sdnd = nd if sdnd is None else sdnd
    return f"${agg['mean']:.{nd}f}\\!\\pm\\!{agg['sd']:.{sdnd}f}$"


def sg(x, nd=2):
    return f"${x:+.{nd}f}$"


def ci(pooled, nd=2, key_d="delta_pp"):
    d, (lo, hi) = pooled[key_d], pooled["ci95_pp"]
    return f"${d:+.{nd}f}$\\,[${lo:+.{nd}f}$,\\,${hi:+.{nd}f}$]"


def pm1(pooled_list):
    """'Yes' if every CI lies inside (-1, +1) pp, else 'No (<protocols>)'."""
    bad = [p for p, q in pooled_list if not q["within_pm1pp"]]
    return "Yes" if not bad else "\\begin{tabular}[t]{@{}l@{}}No (" + ",\\\\".join(bad) + ")\\end{tabular}"


# ============================================================================= B1: merged dissociation table
def t_dissociation_merged():
    trio, mgc = J("c100_trio"), J("mgc_c100")
    tp, mp, c10 = J("c100_trio_paired"), J("mgc_paired_bootstrap"), J("c10_paired")
    V = trio["variants"]
    rows = []

    def acc_row(label, agg, sep_agg, bold=None):
        cells = [label, pm(sep_agg)] + [pm(agg[p]) for p in PROT] + [""]
        return " & ".join(cells) + " \\\\"

    def delta_row(pairs):
        cells = ["\\quad $\\Delta$ vs.\\ cum.", ""] + [ci(q) for _, q in pairs] + [pm1(pairs)]
        return " & ".join(cells) + " \\\\"

    rows.append(acc_row("$\\gamma{=}0$ (local)", V["gamma0"]["agg"], V["gamma0"]["agg"]["sep_curr_nl_deepest"]))
    rows.append(delta_row([(p, tp["pairs"][p]["gamma0_minus_cumulative"]["pooled"]) for p in PROT]))
    rows.append(acc_row("Gated $\\kappa{=}0$", V["gated_k0"]["agg"], V["gated_k0"]["agg"]["sep_curr_nl_deepest"]))
    rows.append(delta_row([(p, tp["pairs"][p]["gated_k0_minus_cumulative"]["pooled"]) for p in PROT]))
    rows.append(acc_row("Cumulative", V["cumulative"]["agg"], V["cumulative"]["agg"]["sep_curr_nl_deepest"]))
    rows.append(acc_row("MGC", mgc["mgc"]["agg"], mgc["mgc"]["agg"]["sep_curr_nl_deepest"]))
    rows.append(delta_row([(p, mp["mgc_minus_cumulative"][p]["pooled"]) for p in PROT]))
    fv = mgc["four_variant_c100"]
    rng = fv["range_pp_per_protocol"]
    range_row = " & ".join(["Range", f"${fv['deepest_sep_max_over_min_unrounded']:.2f}{{\\times}}$"]
                           + [f"${rng[p]:.2f}$\\,pp" for p in PROT] + [""]) + " \\\\"
    c10p = c10["cp_fair_minus_gamma0"]
    c10_row = " & ".join(["C10 pair", "---"]
                         + [ci(c10p[p]["pooled"]) for p in PROT]
                         + [pm1([(p, {"within_pm1pp": c10p[p]["pooled"]["within_pm1pp"]}) for p in PROT])]) + " \\\\"
    minp = c10["min_mcnemar_p_tta_protocols_floor_2dp"]
    # Phase 6 (B1): this table replaces the submitted main-text Table 3 and absorbs the appendix
    # duplicates (tab:dissociation, tab:paired_dissociation, tab:dissociation_ci). The caption carries
    # the adopted rebuttal interpretation. Churn range: trio S2-TTA pair means (min) to MGC-vs-cumulative
    # per-seed S1 (max), both from results/churn.json.
    ch = J("churn")
    churn_lo = min(ch["trio_pairs"]["S2-TTA"][k]["mean"] for k in ch["trio_pairs"]["S2-TTA"])
    churn_hi = max(ch["mgc_vs_cumulative"]["S1"]["per_seed"].values())
    # Verifier round (F19): the heuristic repairs' S1 CIs vs cumulative exclude 0 (inside +-1 pp);
    # gamma=0's S1-TTA CI does too. Assert so the caption sentence cannot go stale silently.
    heur = {v: tp["pairs"][p][f"{v}_minus_cumulative"]["pooled"] for v in ("gamma0", "gated_k0") for p in ("S1",)}
    assert all(q["ci95_pp"][1] < 0 and q["within_pm1pp"] for q in heur.values()), heur
    g0_s1tta = tp["pairs"]["S1-TTA"]["gamma0_minus_cumulative"]["pooled"]["ci95_pp"]
    k0_s1tta = tp["pairs"]["S1-TTA"]["gated_k0_minus_cumulative"]["pooled"]["ci95_pp"]
    assert g0_s1tta[1] < 0 and not (k0_s1tta[1] < 0), (g0_s1tta, k0_s1tta)
    # Verifier round (F5): resumed trio runs = layer log starting after epoch 1 (each has an earlier
    # aborted directory holding epochs 1..N-1); MGC seed 456 is the fourth-arm resume.
    resumed_trio = sum(1 for v in V.values() for ps in v["per_seed"].values() if ps["first_stage1_epoch_logged"] > 1)
    n_trio = sum(len(v["per_seed"]) for v in V.values())
    assert mgc["mgc"]["per_seed"]["456"]["first_stage1_epoch_logged"] > 1
    body = rf"""\begin{{table}}[!tb]
  \caption{{\textbf{{Central dissociation under four readout protocols (CIFAR-100, dense L4/D256, 3~seeds).}}
           sep: deepest-block $\text{{sep}}^\text{{cur}}_\text{{nl}}$ (L3) at the last Stage-1 epoch.
           Accuracy: test top-1 (\%) of the validation-selected checkpoints (S1: EMA backbone; S2: trained head
           on the frozen EMA backbone), mean $\pm$ sample SD.
           Gated: hardness-gated $\kappa{{=}}0$; cumulative: $\gamma{{=}}0.7$; MGC: $c_d{{=}}1$ (\S\ref{{sec:method}}).
           $\Delta$ rows: paired difference to the cumulative arm on matched seeds ($n{{=}}30{{,}}000$ test
           predictions) with a 5000-resample bootstrap 95\% CI, conditional on the trained checkpoints;
           per-seed deltas are in App.~\ref{{app:mgc_results}} (MGC) and App.~\ref{{app:churn}} (trio).
           ``$\pm1$\,pp?'': every CI lies inside $\pm1$\,pp. Range: over the unrounded variant means.
           The heuristic repairs move no protocol by 1\,pp, although both sit slightly below cumulative at S1
           ($\gamma{{=}}0$ also at S1-TTA), with CIs that exclude 0 but stay inside $\pm1$\,pp; MGC pays a
           consistent Stage-1 cost (negative in all 3 seeds under both S1 protocols) that the trained
           Stage-2 probe recovers. Accuracy invariance is a property of the deployed scoring rule (exact
           only under redistribution, Prop.~\ref{{prop:redistribution}}) and, empirically, of the structured
           readouts we test, not of what the network learns: {churn_lo:.0f}--{churn_hi:.0f}\% of test predictions
           change between variants (App.~\ref{{app:churn}}). MGC seed~456 and {resumed_trio} of the {n_trio} trio runs
           were resumed from checkpoints (App.~Tabs.~\ref{{tab:mgc_full}}
           and~\ref{{tab:cifar100_dissociation_multiseed}}). C10 pair: $\Delta$ [95\% CI] of \textsc{{cp-fair}} $-$ $\gamma{{=}}0$ on CIFAR-10
           (L4/D256, 3 seeds $\times$ 10k test images; per-seed exact McNemar $p{{>}}{minp:.2f}$ under TTA;
           $\gamma{{=}}0$ seed~42 used a different configuration from seeds 123/456).}}
  \label{{tab:dissociation_merged}}
  \centering
  \footnotesize
  \setlength{{\tabcolsep}}{{1.5pt}}
  \resizebox{{\textwidth}}{{!}}{{%
  \begin{{tabular}}{{lcccccl}}
    \toprule
    Variant & sep (L3) & S1 & S1-TTA & S2 & S2-TTA & $\pm1$\,pp? \\
    \midrule
""" + "\n".join("    " + r for r in rows) + rf"""
    \midrule
    {range_row}
    \midrule
    {c10_row}
    \bottomrule
  \end{{tabular}}%
  }}
\end{{table}}
"""
    write("t_dissociation_merged", ["c100_trio", "mgc_c100", "c100_trio_paired", "mgc_paired_bootstrap", "c10_paired", "churn"], body)


# ============================================================================= C1/C2: MGC per-seed table
def t_mgc():
    m, d = J("mgc_c100"), J("mgc_d128")
    rows = []
    mg, cum, dl = m["mgc"], m["cumulative"], m["delta_mgc_minus_cumulative_pp"]
    for i, s in enumerate(SEEDS):
        ps = mg["per_seed"][s]
        acc = [f"{ps[p]:.2f} (${dl[p]['values'][i]:+.2f}$)" for p in PROT]
        sep = [num(x) for x in ps["sep_curr_nl"]]
        lam = [num(x) for x in ps["lam_mean_final"][1:]]
        tag = s + ("$^\\dagger$" if s == "456" else "")
        rows.append(" & ".join(([r"\multirow{5}{*}{\shortstack[l]{CIFAR-100\\L4/D256\\(SAM off)}}"] if i == 0 else [""]) + [tag] + acc + sep + lam) + " \\\\")
    a = mg["agg"]
    rows.append(" & ".join(["", "mean"] + [f"{a[p]['mean']:.2f}$\\pm${a[p]['sd']:.2f} (${dl[p]['mean']:+.2f}$)" for p in PROT]
                           + [f"{x['mean']:.2f}$\\pm${x['sd']:.2f}" for x in a["sep_curr_nl_per_block"]]
                           + [num(x["mean"]) for x in a["lam_mean_final_per_block"][1:]]) + " \\\\")
    c = cum["agg"]
    rows.append(" & ".join(["", "cum."] + [f"{c[p]['mean']:.2f}$\\pm${c[p]['sd']:.2f}" for p in PROT]
                           + [f"{x['mean']:.2f}$\\pm${x['sd']:.2f}" for x in c["sep_curr_nl_per_block"]] + ["---"] * 3) + " \\\\")
    rows.append("\\midrule")
    g = d["mgc"]
    for i, s in enumerate(SEEDS):
        ps = g["per_seed"][s]
        rows.append(" & ".join(([r"\multirow{4}{*}{\shortstack[l]{CIFAR-10\\L4/D128\\(SAM on)}}"] if i == 0 else [""])
                               + [s + ("$^\\ddagger$" if s == "42" else "")] + [f"{ps[p]:.2f}" for p in PROT]
                               + [num(x) for x in ps["sep_curr_nl"]] + [num(x) for x in ps["lam_mean_final"][1:]]) + " \\\\")
    a = g["agg"]
    rows.append(" & ".join(["", "mean"] + [f"{a[p]['mean']:.2f}$\\pm${a[p]['sd']:.2f}" for p in PROT]
                           + [f"{x['mean']:.2f}$\\pm${x['sd']:.2f}" for x in a["sep_curr_nl_per_block"]]
                           + [num(x["mean"]) for x in a["lam_mean_final_per_block"][1:]]) + " \\\\")
    lw = m["lambda_telemetry"]["seed42_whole_training_mean_lambda_per_block"][1:]
    anc = d["seed42_sam_off_anchors"]
    # Verifier round (F3): list every anchor under S1, S1-TTA and S2-TTA, not only the S1 values, so the
    # caption shows that MGC's L4/D128 gap is single-crop S1 only (S1-TTA ties gamma=0, S2-TTA ties kappa=0).
    ak = ("gamma07_constant", "gamma0_no_all_collab", "gated_k0_t1")

    def anc3(p):
        return "/".join(num(anc[k][p]) for k in ak)

    body = rf"""\begin{{table}}[!htb]
  \caption{{\textbf{{Missing-gradient compensation (MGC, $c_d{{=}}1$) per seed.}} Test top-1 (\%) of
           the validation-selected EMA checkpoints; in parentheses, the paired difference to the
           cumulative ($\gamma{{=}}0.7$) arm on the same seed. sep: $\text{{sep}}^\text{{cur}}_\text{{nl}}$
           per block at the last Stage-1 epoch; $\bar\lambda$: final-epoch mean compensation weight
           (block~0 has no compensator, $\bar\lambda{{\equiv}}0$). The MGC arm replaces the baseline's
           depth-scaled current-block term, so block~0 also loses its auxiliary. Seed-42 whole-training
           mean $\bar\lambda$ (CIFAR-100): {num(lw[0])}/{num(lw[1])}/{num(lw[2])}.
           Faithful implementation ($\epsilon{{=}}10^{{-6}}$, positive-part clamp; only the mean and p95
           of $\lambda$ are logged). $^\dagger$Resumed run: layer log starts at epoch
           {m['mgc']['per_seed']['456']['first_stage1_epoch_logged']} (final evaluation complete).
           $^\ddagger$Local run; seeds 123/456 ran on Colab. The seed-42 L4/D128 SAM-off anchors
           ($\gamma{{=}}0.7$/$\gamma{{=}}0$/$\kappa{{=}}0$) reach S1 {anc3('S1')}, S1-TTA {anc3('S1-TTA')}, and
           S2-TTA {anc3('S2-TTA')}; these single-seed comparisons cross the SAM setting.}}
  \label{{tab:mgc_full}}
  \centering
  \scriptsize
  \setlength{{\tabcolsep}}{{2pt}}
  \resizebox{{\textwidth}}{{!}}{{%
  \begin{{tabular}}{{llccccccccccc}}
    \toprule
    & & \multicolumn{{4}}{{c}}{{Test top-1 (\%)}} & \multicolumn{{4}}{{c}}{{$\text{{sep}}^\text{{cur}}_\text{{nl}}$ per block}} & \multicolumn{{3}}{{c}}{{$\bar\lambda$ per block}} \\
    \cmidrule(lr){{3-6}} \cmidrule(lr){{7-10}} \cmidrule(lr){{11-13}}
    Setting & Seed & S1 & S1-TTA & S2 & S2-TTA & L0 & L1 & L2 & L3 & L1 & L2 & L3 \\
    \midrule
""" + "\n".join("    " + r for r in rows) + r"""
    \bottomrule
  \end{tabular}%
  }
\end{table}
"""
    write("t_mgc", ["mgc_c100", "mgc_d128"], body)


# ============================================================================= C5: squared hinge
def t_hinge():
    h = J("hinge")
    A = h["arms"]
    rows = []
    for key, label in (("gamma0.7", "Cumulative $\\gamma{=}0.7$"), ("gamma0", "Block-local $\\gamma{=}0$")):
        a = A[key]["agg"]
        sepb = a["sep_curr_nl_per_block"]
        rows.append(" & ".join([label] + [pm(a[p]) for p in PROT] + [pm(sepb[0]), pm(sepb[-1])]) + " \\\\")
    dd = h["delta_gamma07_minus_gamma0_pp"]
    rows.append("\\midrule")
    rows.append(" & ".join(["$\\Delta$ ($\\gamma{=}0.7$ $-$ $\\gamma{=}0$); sep ratio $\\gamma{=}0/\\gamma{=}0.7$"] + [sg(dd[p]) for p in PROT]
                           + ["---", f"${h['deepest_sep_ratio_gamma0_over_gamma07']:.2f}{{\\times}}$"]) + " \\\\")
    body = rf"""\begin{{table}}[!htb]
  \caption{{\textbf{{Squared-hinge replication}} (barrier $\max(0,\theta-u)^2$, $\theta{{=}}2$; CIFAR-10
           L4/D128, 180+10 epochs, SAM on, 3 seeds per arm, mean $\pm$ sample SD). The deepest block
           loses separation under the cumulative objective while block~0 is unchanged, and test
           accuracy differs between the arms by at most {num(max(abs(v) for v in dd.values()))}\,pp. All seeds come from one run lineage; the
           $\gamma{{=}}0.7$ seed-456 layer log is a resumed suffix starting at epoch
           {h['arms']['gamma0.7']['per_seed']['456']['first_stage1_epoch_logged']}.}}
  \label{{tab:hinge}}
  \centering
  \small
  \setlength{{\tabcolsep}}{{3pt}}
  \resizebox{{\textwidth}}{{!}}{{%
  \begin{{tabular}}{{lcccccc}}
    \toprule
    Arm & S1 & S1-TTA & S2 & S2-TTA & sep (L0) & sep (L3) \\
    \midrule
""" + "\n".join("    " + r for r in rows) + r"""
    \bottomrule
  \end{tabular}%
  }
\end{table}
"""
    write("t_hinge", ["hinge"], body)


# ============================================================================= C7: gradient share
def t_gradshare():
    g = J("gradient_share")
    A = g["arms"]

    def cells(arm, term):
        out = []
        for b in A[arm]["per_block"]:
            t = b["terms"].get(term)
            out.append("---" if t is None else f"{t['share']:.3f} ({t['cos']:.2f})")
        return out

    rows = [
        " & ".join(["$\\gamma{=}0.7$ (constant)", "discrimination (cum.)"] + cells("gamma0.7", "block_cum")) + " \\\\",
        " & ".join(["", "current-block aux."] + cells("gamma0.7", "block_curr")) + " \\\\",
        " & ".join(["$\\gamma{=}0$", "discrimination (cum.)"] + cells("gamma0", "block_cum")) + " \\\\",
        " & ".join(["MGC ($c_d{=}1$)", "discrimination (cum.)"] + cells("mgc", "block_cum")) + " \\\\",
        " & ".join(["", "MGC local term"] + cells("mgc", "mgc_local")) + " \\\\",
    ]
    nb = A["mgc"]["n_batches"]
    body = rf"""\begin{{table}}[!htb]
  \caption{{\textbf{{Per-term gradient share at convergence}} (seed~42, CIFAR-10 L4/D128 gated-ablation
           arms and MGC; raw training weights, not EMA). Share $=\|\nabla_t\|/\|\nabla_\text{{total}}\|$
           over each block's own parameters, mean over {nb} training batches; in parentheses
           $\cos(\nabla_t,\nabla_\text{{total}})$. ``Discrimination (cum.)'' is the loss on cumulative
           goodness (the term of Thm.~3.1). Term gradients sum to the total gradient up to a relative
           error below $3{{\times}}10^{{-4}}$ at block~0 and ${{\le}}10^{{-6}}$ at blocks 1--3. MGC was trained
           with SAM, the two gated arms without.}}
  \label{{tab:gradshare}}
  \centering
  \small
  \setlength{{\tabcolsep}}{{3pt}}
  \begin{{tabular}}{{llcccc}}
    \toprule
    Arm & Term & Block 0 & Block 1 & Block 2 & Block 3 \\
    \midrule
""" + "\n".join("    " + r for r in rows) + r"""
    \bottomrule
  \end{tabular}
\end{table}
"""
    write("t_gradshare", ["gradient_share"], body)


# ============================================================================= C8/C9: frozen-backbone readouts
def t_readouts():
    s = J("s2ff_mgc")
    T, M, MA = s["trio_seed42"], s["mgc_per_seed"]["42"], s["mgc_agg"]
    order = [("goodness_sum_S1", "Goodness sum (deployed S1 rule)"),
             ("strict_ff_block_alone", "Strict-FF readout block alone"),
             ("strict_ff_plus_sum", "Strict-FF block $+$ frozen goodness"),
             ("ce_block_alone", "CE-trained block alone"),
             ("ce_plus_sum", "CE-trained block $+$ frozen goodness"),
             ("s2_attentive_probe", "Stage-2 attentive head (probe, not FF)")]
    rows = []
    for k, lab in order:
        rows.append(" & ".join([lab] + [f"{T[v][k]:.2f}" for v in ("gamma0", "gated_k0", "cumulative")]
                               + [f"{M[k]:.2f}", pm(MA[k])]) + " \\\\")
        if k == "ce_plus_sum":
            rows.append("\\midrule")
    mm = s["matched_seed42_mgc_minus_trio_strict_ff_alone_pp"]
    # Phase 6 (C8) caption fix: 'at most 0.27 pp' holds for the three original seed-42 backbones only;
    # on the MGC seed-42 backbone CE moves the block by 0.40 pp (computed from the same JSON).
    ce_d = s["ce_minus_strict_ff_block_alone_pp"]
    ce_trio_max = max(abs(ce_d[v]) for v in ("gamma0", "gated_k0", "cumulative"))
    ce_mgc42 = M["ce_block_alone"] - M["strict_ff_block_alone"]
    body = rf"""\begin{{table}}[!htb]
  \caption{{\textbf{{Frozen-backbone readouts}} (CIFAR-100 L4/D256, single crop, full 10k test, top-1 \%).
           All readout blocks see the frozen Stage-1 backbone only; the Stage-2 attentive head is a
           representation probe, not part of the FF method. Seed-42 columns are matched; the 3-seed
           MGC column is compared only with itself. On matched seed~42 the strict-FF block on the MGC
           backbone is {sg(mm['cumulative'])}/{sg(mm['gated_k0'])}/{sg(mm['gamma0'])}\,pp above cumulative/$\kappa{{=}}0$/$\gamma{{=}}0$,
           and the gap closes once frozen-block goodness is added (span {num(s['seed42_strict_ff_plus_sum_span_pp'])}\,pp).
           Cross-entropy training moves the block by at most {num(ce_trio_max)}\,pp on the three original
           seed-42 backbones, by {num(ce_mgc42)}\,pp on the MGC seed-42 backbone, and by {num(ce_d['mgc_mean'])}\,pp
           for the MGC 3-seed means.
           Goodness-sum row: logged S1 (the readout runs reproduce it within {num(s['S1_logged_vs_readout_recompute_max_abs_diff_pp'])}\,pp).}}
  \label{{tab:readouts}}
  \centering
  \small
  \setlength{{\tabcolsep}}{{3pt}}
  \resizebox{{\textwidth}}{{!}}{{%
  \begin{{tabular}}{{lccccc}}
    \toprule
    Readout on frozen backbone & $\gamma{{=}}0$ (s42) & $\kappa{{=}}0$ (s42) & Cum.\ (s42) & MGC (s42) & MGC (3 seeds) \\
    \midrule
""" + "\n".join("    " + r for r in rows) + r"""
    \bottomrule
  \end{tabular}%
  }
\end{table}
"""
    write("t_readouts", ["s2ff_mgc"], body)


# ============================================================================= C10: probes
def t_probes():
    p, trio = J("probes"), J("c100_trio")
    P = p["panels"]
    V = ("gamma0", "gated_k0", "cumulative")
    rows = []

    def anchor(label, prot):
        ag = {v: trio["variants"][v]["agg"][prot] for v in V}
        span = max(a["mean"] for a in ag.values()) - min(a["mean"] for a in ag.values())
        return " & ".join([label] + [pm(ag[v]) for v in V] + [num(span)]) + " \\\\"

    def prow(key, label):
        pv = P[key]["per_variant"]
        return " & ".join([label] + [pm(pv[v]) for v in V] + [num(P[key]["trio_span_pp"])]) + " \\\\"

    rows.append(anchor("Goodness sum (S1, deployed)", "S1"))
    rows.append(anchor("Stage-2 attentive probe (S2)", "S2"))
    rows.append("\\midrule")
    rows.append("\\multicolumn{5}{l}{\\emph{400-D goodness, block-softmax normalized}} \\\\")
    rows.append(prow("ridge_goodness_blocksoftmax", "\\quad ridge"))
    rows.append(prow("logistic_goodness_blocksoftmax", "\\quad logistic"))
    rows.append(prow("knn10cos_goodness_blocksoftmax", "\\quad 10-NN (cosine)"))
    rows.append("\\multicolumn{5}{l}{\\emph{400-D goodness, raw}} \\\\")
    rows.append(prow("logistic_goodness_flat", "\\quad logistic"))
    rows.append(prow("knn10cos_goodness_flat", "\\quad 10-NN (cosine)"))
    rows.append("\\multicolumn{5}{l}{\\emph{Block-3 goodness only (100-D)}} \\\\")
    rows.append(prow("logistic_goodness_block3", "\\quad logistic"))
    rows.append(prow("knn10cos_goodness_block3", "\\quad 10-NN (cosine)"))
    rows.append("\\multicolumn{5}{l}{\\emph{Pooled embedding, all blocks (mean label token)}} \\\\")
    rows.append(prow("logistic_pooled_meanemb_concat", "\\quad logistic"))
    rows.append(prow("knn10cos_pooled_meanemb_concat", "\\quad 10-NN (cosine)"))
    rows.append("\\multicolumn{5}{l}{\\emph{Pooled embedding, block 3 (mean label token)}} \\\\")
    rows.append(prow("logistic_pooled_meanemb_block3", "\\quad logistic"))
    rows.append(prow("knn10cos_pooled_meanemb_block3", "\\quad 10-NN (cosine)"))
    z = {k: num(P[k]["trio_span_pp"]) for k in ("logistic_pooled_zerotok_concat", "knn10cos_pooled_zerotok_concat",
                                                  "logistic_pooled_zerotok_block3", "knn10cos_pooled_zerotok_block3")}
    body = rf"""\begin{{table}}[!htb]
  \caption{{\textbf{{Label-free probes on the frozen CIFAR-100 trio}} (fit on each run's own 5k validation
           split, evaluated once on the full 10k test; top-1 \%, mean $\pm$ sample SD over 3 seeds; span =
           max $-$ min of the unrounded variant means). Structured readouts of the goodness scores keep the
           trio within 1\,pp; k-NN stability depends on per-block normalization, and block-3-only and
           pooled-embedding probes are bounded exceptions where the span exceeds 1\,pp. With a zero label
           token the pooled spans are {z['logistic_pooled_zerotok_concat']}/{z['knn10cos_pooled_zerotok_concat']}\,pp (all blocks,
           logistic/10-NN) and {z['logistic_pooled_zerotok_block3']}/{z['knn10cos_pooled_zerotok_block3']}\,pp (block~3).}}
  \label{{tab:probes}}
  \centering
  \small
  \setlength{{\tabcolsep}}{{3pt}}
  \begin{{tabular}}{{lcccc}}
    \toprule
    Readout / probe & $\gamma{{=}}0$ & $\kappa{{=}}0$ & Cumulative & Span (pp) \\
    \midrule
""" + "\n".join("    " + r for r in rows) + r"""
    \bottomrule
  \end{tabular}
\end{table}
"""
    write("t_probes", ["probes", "c100_trio"], body)


# ============================================================================= C11: readout ladder
def t_ladder():
    L = J("readout_ladder")
    V = ("gamma0", "gated_k0", "cumulative")
    PV = L["per_variant"]
    labels = {"R0": "R0: plain goodness sum (deployed)",
              "R1": "R1: per-depth weights $w_d$",
              "R2": "R2: per-depth temperatures ($w_d{>}0$)",
              "R3": "R3: margin-gated $w_d(x)$"}
    rows = []
    for R in ("R0", "R1", "R2", "R3"):
        cells = [labels[R]]
        for v in V:
            a = PV[v]["eval_acc_pp"][R]
            c = pm(a)
            if R != "R0":
                gnn = PV[v]["gain_vs_R0_pp"][R]
                c += f" (${gnn['mean']:+.2f}\\!\\pm\\!{gnn['sd']:.2f}$)"
            cells.append(c)
        cells.append(num(L["trio_span_pp_per_rung"][R]))
        rows.append(" & ".join(cells) + " \\\\")
    dg = L["differential_gain_R1"]
    rows.append("\\midrule")
    rows.append(" & ".join(["R1 gain minus cumulative's R1 gain [95\\% CI]",
                            ci({"delta_pp": dg["gamma0_minus_cumulative"]["diff_pp"], "ci95_pp": dg["gamma0_minus_cumulative"]["ci95_pp"]}),
                            ci({"delta_pp": dg["gated_k0_minus_cumulative"]["diff_pp"], "ci95_pp": dg["gated_k0_minus_cumulative"]["ci95_pp"]}),
                            "---", ""]) + " \\\\")
    body = rf"""\begin{{table}}[!htb]
  \caption{{\textbf{{Validation-fitted readout ladder on the frozen CIFAR-100 trio}} (exploratory and
           checkpoint-conditional). Each readout is fit on the run's own 5k validation split and evaluated
           once on the full 10k test (S1 single crop, EMA weights); top-1 \%, mean $\pm$ sample SD over
           3 seeds, in parentheses the gain over R0. R2 equals R1 restricted to positive weights, so the
           two coincide whenever the fitted R1 weights are positive. The trio span stays at most
           {num(max(L['trio_span_pp_per_rung'].values()))}\,pp at every rung, while the learned weights help the
           $\gamma{{=}}0$ and $\kappa{{=}}0$ variants more than the cumulative one (last row: paired 5000-resample
           bootstrap over the test set).
           R0 is recomputed from the dumped scores and matches the logged S1 within {num(L['R0_vs_logged_S1_max_abs_diff_pp'])}\,pp.}}
  \label{{tab:readout_ladder}}
  \centering
  \small
  \setlength{{\tabcolsep}}{{3pt}}
  \resizebox{{\textwidth}}{{!}}{{%
  \begin{{tabular}}{{lcccc}}
    \toprule
    Readout & $\gamma{{=}}0$ & $\kappa{{=}}0$ & Cumulative & Span (pp) \\
    \midrule
""" + "\n".join("    " + r for r in rows) + r"""
    \bottomrule
  \end{tabular}%
  }
\end{table}
"""
    write("t_ladder", ["readout_ladder"], body)


# ============================================================================= trio per-seed paired deltas (App. B.7)
def t_trio_perseed():
    """Verifier round (F16): Table 3 prints pooled paired CIs; the per-seed paired deltas of the trio
    pairs live here (MGC's per-seed deltas are in tab:mgc_full)."""
    tp = J("c100_trio_paired")
    pairs = (("gamma0_minus_cumulative", "$\\gamma{=}0$ $-$ cumulative"),
             ("gated_k0_minus_cumulative", "$\\kappa{=}0$ $-$ cumulative"),
             ("gamma0_minus_gated_k0", "$\\gamma{=}0$ $-$ $\\kappa{=}0$"))
    rows, big = [], []
    for key, label in pairs:
        cells = [label]
        for p in PROT:
            ps = tp["pairs"][p][key]["per_seed"]
            cells.append("/".join(f"${ps[s]['delta_pp']:+.2f}$" for s in SEEDS))
            big += [(label, p, s, ps[s]["delta_pp"]) for s in SEEDS if abs(ps[s]["delta_pp"]) > 1.0]
        rows.append(" & ".join(cells) + " \\\\")
    assert all(tp["pairs"][p][k]["pooled"]["within_pm1pp"] for p in PROT for k, _ in pairs)
    assert len(big) == 1, big  # the caption sentence below names exactly one exceedance
    bl, bp, bs, bv = big[0]
    body = rf"""\begin{{table}}[!htb]
  \caption{{\textbf{{Per-seed paired differences of the CIFAR-100 trio}} (pp, seeds 42/123/456; each on the
           seed's full 10k test set). The pooled differences and their 5000-resample bootstrap CIs are in
           Table~\ref{{tab:dissociation_merged}} (vs.\ cumulative) and App.~\ref{{app:churn}}; every pooled CI of
           the three pairs lies inside $\pm1$\,pp under all four protocols, while one per-seed value exceeds
           1\,pp in magnitude ({bl}, {bp}, seed {bs}: ${bv:+.2f}$). MGC's per-seed differences are in
           Table~\ref{{tab:mgc_full}}.}}
  \label{{tab:trio_perseed}}
  \centering
  \small
  \setlength{{\tabcolsep}}{{3pt}}
  \resizebox{{\textwidth}}{{!}}{{%
  \begin{{tabular}}{{lcccc}}
    \toprule
    Pair & S1 & S1-TTA & S2 & S2-TTA \\
    \midrule
""" + "\n".join("    " + r for r in rows) + r"""
    \bottomrule
  \end{tabular}%
  }
\end{table}
"""
    write("t_trio_perseed", ["c100_trio_paired"], body)


# ============================================================================= C6: BP rows for Table 2
def t_bp_rows():
    b = J("bp_calibration")
    R = b["rows"]

    def mparams(key):
        return R[key]["per_seed"]["42"]["n_params_millions"]

    spec = [
        ("plain_cnn_bp", f"Plain CNN ({mparams('plain_cnn_bp'):.2f}\\,M, ch.\\ 64/128/256)", "BP", "strong"),
        ("plain_cnn_ff", f"Plain CNN ({mparams('plain_cnn_ff'):.2f}\\,M, ch.\\ 64/128/256)", "FF", "FF-pipeline"),
        ("bp_weak", f"FF backbone (stripped, {mparams('bp_weak'):.2f}\\,M)", "BP", "weak"),
        ("bp_strong", f"FF backbone (stripped, {mparams('bp_strong'):.2f}\\,M)", "BP", "BP-strong"),
    ]
    lines = ["% Rows for Table 2 (tab:bp_ff_ablation), columns: Architecture & Training & Aug. & Val Top-1 & Test no-TTA & Test TTA.",
             "% Usage: \\input{tables/t_bp_rows} before the table (it only defines a macro), then write \\BPRowsNThree",
             "% inside the tabular. (A bare \\input inside a tabular followed by \\bottomrule/\\midrule fails with 'Misplaced \\noalign'.)",
             "% All four rows are n=3 (seeds 42/123/456; mean +- sample SD). Per-seed test top-1:"]
    for key, *_ in spec:
        v = R[key]["test_top1"]["values"]
        lines.append(f"%   {key}: " + " / ".join(f"{x:.2f}" for x in v))
    lines.append(f"% Co-design gap (plain CNN BP - FF) = {b['co_design_gap_pp']:.2f} pp; augmentation effect (BP strong - weak) = {b['augmentation_effect_pp']:.2f} pp.")
    lines.append("\\providecommand{\\BPRowsNThree}{}")
    lines.append("\\renewcommand{\\BPRowsNThree}{%")
    for key, arch, tr, aug in spec:
        lines.append("  " + " & ".join([arch, tr, aug, pm(R[key]["val_top1"]), pm(R[key]["test_top1"]), "---"]) + " \\\\")
    lines.append("}")
    write("t_bp_rows", ["bp_calibration"], "\n".join(lines) + "\n")


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    t_dissociation_merged()
    t_mgc()
    t_hinge()
    t_gradshare()
    t_readouts()
    t_probes()
    t_ladder()
    t_trio_perseed()
    t_bp_rows()


if __name__ == "__main__":
    main()
