#!/usr/bin/env bash
# Reproduce the central negative result (Tab. 3, CIFAR-100 dissociation).
# 3 variants x 3 seeds = 9 runs (dense, no MoE, no SAM, 362+20 epochs).
# The paired-bootstrap step reads the S2-TTA prediction files bundled in preds_cifar100/ (30 MB,
# published with this code; see preds_cifar100/README.md) or regenerated by the runs.
set -euo pipefail
cd "$(dirname "$0")/.."

for SEED in 42 123 456; do
  # gamma=0 (purely local)
  FF_NUM_BLOCKS=4 FF_D_MODEL=256 FF_NUM_HEADS=8 \
    FF_USE_SAM=0 FF_N_EXPERTS=1 FF_MOE_TOP_K=1 \
    FF_GAMMA_SCALE=0 FF_SEED=$SEED \
    python trainers/cp_fair_cifar100.py

  # adaptive kappa=0
  FF_NUM_BLOCKS=4 FF_D_MODEL=256 FF_NUM_HEADS=8 \
    FF_USE_SAM=0 FF_N_EXPERTS=1 FF_MOE_TOP_K=1 \
    FF_GAMMA_GATING_MODE=adaptive FF_GAMMA_0=0.7 \
    FF_GAMMA_KAPPA=0.0 FF_GAMMA_TAU=1.0 FF_SEED=$SEED \
    python trainers/cp_fair_cifar100.py

  # cumulative gamma=0.7
  FF_NUM_BLOCKS=4 FF_D_MODEL=256 FF_NUM_HEADS=8 \
    FF_USE_SAM=0 FF_N_EXPERTS=1 FF_MOE_TOP_K=1 \
    FF_GAMMA_SCALE=0.7 FF_SEED=$SEED \
    python trainers/cp_fair_cifar100.py
done

# Recompute paired-bootstrap CIs from bundled predictions
FF_C100_PREDS="${FF_C100_PREDS:-preds_cifar100}" python analysis/paired_dissociation_stats.py
echo "Paired CI summary: analysis/60_paired_dissociation.json (camera-ready values: metric_summaries/camera_ready/c100_trio_paired.json)"
